/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.ui.tests;

import com.google.inject.Injector;
import fil.xtext.langFil.ui.internal.LangFilActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LangFilUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangFilActivator.getInstance().getInjector("fil.xtext.LangFil");
	}

}
