/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLangFilScopeProvider extends DelegatingScopeProvider {
}
