/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fil.xtext.LangFilRuntimeModule;
import fil.xtext.LangFilStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LangFilIdeSetup extends LangFilStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LangFilRuntimeModule(), new LangFilIdeModule()));
	}
	
}
