/*
 * generated by Xtext 2.25.0
 */
package fil.xtextfil.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LangFilGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class FaculteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtextfil.LangFil.Faculte");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFaculteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNomKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNomAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNomEStringParserRuleCall_3_0 = (RuleCall)cNomAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNiveauxKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cNiveauxAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cNiveauxNiveauParserRuleCall_4_2_0 = (RuleCall)cNiveauxAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cNiveauxAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cNiveauxNiveauParserRuleCall_4_3_1_0 = (RuleCall)cNiveauxAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIntervenantsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cIntervenantsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cIntervenantsIntervenantParserRuleCall_5_2_0 = (RuleCall)cIntervenantsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cIntervenantsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cIntervenantsIntervenantParserRuleCall_5_3_1_0 = (RuleCall)cIntervenantsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Faculte returns Faculte:
		//    'Faculte'
		//    '{'
		//        'nom' nom=EString
		//        ('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}')?
		//        ('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Faculte'
		//'{'
		//    'nom' nom=EString
		//    ('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}')?
		//    ('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Faculte'
		public Keyword getFaculteKeyword_0() { return cFaculteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'nom'
		public Keyword getNomKeyword_2() { return cNomKeyword_2; }
		
		//nom=EString
		public Assignment getNomAssignment_3() { return cNomAssignment_3; }
		
		//EString
		public RuleCall getNomEStringParserRuleCall_3_0() { return cNomEStringParserRuleCall_3_0; }
		
		//('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'niveaux'
		public Keyword getNiveauxKeyword_4_0() { return cNiveauxKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//niveaux+=Niveau
		public Assignment getNiveauxAssignment_4_2() { return cNiveauxAssignment_4_2; }
		
		//Niveau
		public RuleCall getNiveauxNiveauParserRuleCall_4_2_0() { return cNiveauxNiveauParserRuleCall_4_2_0; }
		
		//( "," niveaux+=Niveau)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//niveaux+=Niveau
		public Assignment getNiveauxAssignment_4_3_1() { return cNiveauxAssignment_4_3_1; }
		
		//Niveau
		public RuleCall getNiveauxNiveauParserRuleCall_4_3_1_0() { return cNiveauxNiveauParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'intervenants'
		public Keyword getIntervenantsKeyword_5_0() { return cIntervenantsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//intervenants+=Intervenant
		public Assignment getIntervenantsAssignment_5_2() { return cIntervenantsAssignment_5_2; }
		
		//Intervenant
		public RuleCall getIntervenantsIntervenantParserRuleCall_5_2_0() { return cIntervenantsIntervenantParserRuleCall_5_2_0; }
		
		//( "," intervenants+=Intervenant)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//intervenants+=Intervenant
		public Assignment getIntervenantsAssignment_5_3_1() { return cIntervenantsAssignment_5_3_1; }
		
		//Intervenant
		public RuleCall getIntervenantsIntervenantParserRuleCall_5_3_1_0() { return cIntervenantsIntervenantParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtextfil.LangFil.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class NiveauElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtextfil.LangFil.Niveau");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNiveauAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNiveauKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNomKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNomAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNomEStringParserRuleCall_3_1_0 = (RuleCall)cNomAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPseudoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPseudoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_4_1_0 = (RuleCall)cPseudoAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Niveau returns Niveau:
		//    {Niveau}
		//    'Niveau'
		//    '{'
		//        ('nom' nom=EString)?
		//        ('pseudo' pseudo=EString)?
		//        //'responsables' '(' responsables+=[Intervenant|ID] ( "," responsables+=[Intervenant|ID])* ')'
		//        //'formations' '{' formations+=Formation ( "," formations+=Formation)* '}'
		//        //('presentation' presentation=Presentation)?
		//        //'ues' '{' ues+=UE ( "," ues+=UE)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Niveau}
		//'Niveau'
		//'{'
		//    ('nom' nom=EString)?
		//    ('pseudo' pseudo=EString)?
		//    //'responsables' '(' responsables+=[Intervenant|ID] ( "," responsables+=[Intervenant|ID])* ')'
		//    //'formations' '{' formations+=Formation ( "," formations+=Formation)* '}'
		//    //('presentation' presentation=Presentation)?
		//    //'ues' '{' ues+=UE ( "," ues+=UE)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Niveau}
		public Action getNiveauAction_0() { return cNiveauAction_0; }
		
		//'Niveau'
		public Keyword getNiveauKeyword_1() { return cNiveauKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('nom' nom=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nom'
		public Keyword getNomKeyword_3_0() { return cNomKeyword_3_0; }
		
		//nom=EString
		public Assignment getNomAssignment_3_1() { return cNomAssignment_3_1; }
		
		//EString
		public RuleCall getNomEStringParserRuleCall_3_1_0() { return cNomEStringParserRuleCall_3_1_0; }
		
		//('pseudo' pseudo=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_4_0() { return cPseudoKeyword_4_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_4_1() { return cPseudoAssignment_4_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_4_1_0() { return cPseudoEStringParserRuleCall_4_1_0; }
		
		//    //'responsables' '(' responsables+=[Intervenant|ID] ( "," responsables+=[Intervenant|ID])* ')'
		//    //'formations' '{' formations+=Formation ( "," formations+=Formation)* '}'
		//    //('presentation' presentation=Presentation)?
		//    //'ues' '{' ues+=UE ( "," ues+=UE)* '}'
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class IntervenantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtextfil.LangFil.Intervenant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntervenantAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntervenantKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNomKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNomAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNomIDTerminalRuleCall_4_0 = (RuleCall)cNomAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPrenomKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPrenomAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPrenomSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cPrenomAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Intervenant returns Intervenant:
		//    {Intervenant}
		//    'Intervenant'
		//    '{'
		//        'nom' nom=ID
		//        ('prenom' prenom=STRING)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Intervenant}
		//'Intervenant'
		//'{'
		//    'nom' nom=ID
		//    ('prenom' prenom=STRING)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Intervenant}
		public Action getIntervenantAction_0() { return cIntervenantAction_0; }
		
		//'Intervenant'
		public Keyword getIntervenantKeyword_1() { return cIntervenantKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'nom'
		public Keyword getNomKeyword_3() { return cNomKeyword_3; }
		
		//nom=ID
		public Assignment getNomAssignment_4() { return cNomAssignment_4; }
		
		//ID
		public RuleCall getNomIDTerminalRuleCall_4_0() { return cNomIDTerminalRuleCall_4_0; }
		
		//('prenom' prenom=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'prenom'
		public Keyword getPrenomKeyword_5_0() { return cPrenomKeyword_5_0; }
		
		//prenom=STRING
		public Assignment getPrenomAssignment_5_1() { return cPrenomAssignment_5_1; }
		
		//STRING
		public RuleCall getPrenomSTRINGTerminalRuleCall_5_1_0() { return cPrenomSTRINGTerminalRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final FaculteElements pFaculte;
	private final EStringElements pEString;
	private final NiveauElements pNiveau;
	private final IntervenantElements pIntervenant;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LangFilGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFaculte = new FaculteElements();
		this.pEString = new EStringElements();
		this.pNiveau = new NiveauElements();
		this.pIntervenant = new IntervenantElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fil.xtextfil.LangFil".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Faculte returns Faculte:
	//    'Faculte'
	//    '{'
	//        'nom' nom=EString
	//        ('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}')?
	//        ('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
	//    '}';
	public FaculteElements getFaculteAccess() {
		return pFaculte;
	}
	
	public ParserRule getFaculteRule() {
		return getFaculteAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Niveau returns Niveau:
	//    {Niveau}
	//    'Niveau'
	//    '{'
	//        ('nom' nom=EString)?
	//        ('pseudo' pseudo=EString)?
	//        //'responsables' '(' responsables+=[Intervenant|ID] ( "," responsables+=[Intervenant|ID])* ')'
	//        //'formations' '{' formations+=Formation ( "," formations+=Formation)* '}'
	//        //('presentation' presentation=Presentation)?
	//        //'ues' '{' ues+=UE ( "," ues+=UE)* '}'
	//    '}';
	public NiveauElements getNiveauAccess() {
		return pNiveau;
	}
	
	public ParserRule getNiveauRule() {
		return getNiveauAccess().getRule();
	}
	
	//Intervenant returns Intervenant:
	//    {Intervenant}
	//    'Intervenant'
	//    '{'
	//        'nom' nom=ID
	//        ('prenom' prenom=STRING)?
	//    '}';
	public IntervenantElements getIntervenantAccess() {
		return pIntervenant;
	}
	
	public ParserRule getIntervenantRule() {
		return getIntervenantAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
