/*
 * generated by Xtext 2.25.0
 */
package fil.xtextfil.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LangFilUiModule extends AbstractLangFilUiModule {

	public LangFilUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
