/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LangFilGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class FaculteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Faculte");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFaculteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFaculteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cNiveauxAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cNiveauxNiveauParserRuleCall_3_0_0 = (RuleCall)cNiveauxAssignment_3_0.eContents().get(0);
		private final Assignment cIntervenantsAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cIntervenantsIntervenantParserRuleCall_3_1_0 = (RuleCall)cIntervenantsAssignment_3_1.eContents().get(0);
		
		//Faculte returns Faculte:
		//    {Faculte}
		//    'Faculte'
		//    name=EString
		//        (niveaux+=Niveau | intervenants+=Intervenant)*
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Faculte}
		//'Faculte'
		//name=EString
		//    (niveaux+=Niveau | intervenants+=Intervenant)*
		public Group getGroup() { return cGroup; }
		
		//{Faculte}
		public Action getFaculteAction_0() { return cFaculteAction_0; }
		
		//'Faculte'
		public Keyword getFaculteKeyword_1() { return cFaculteKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//(niveaux+=Niveau | intervenants+=Intervenant)*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//niveaux+=Niveau
		public Assignment getNiveauxAssignment_3_0() { return cNiveauxAssignment_3_0; }
		
		//Niveau
		public RuleCall getNiveauxNiveauParserRuleCall_3_0_0() { return cNiveauxNiveauParserRuleCall_3_0_0; }
		
		//intervenants+=Intervenant
		public Assignment getIntervenantsAssignment_3_1() { return cIntervenantsAssignment_3_1; }
		
		//Intervenant
		public RuleCall getIntervenantsIntervenantParserRuleCall_3_1_0() { return cIntervenantsIntervenantParserRuleCall_3_1_0; }
	}
	public class DocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Document");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVideoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFichierParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAudioParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Document returns Document:
		//    Video | Fichier | Audio;
		@Override public ParserRule getRule() { return rule; }
		
		//Video | Fichier | Audio
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Video
		public RuleCall getVideoParserRuleCall_0() { return cVideoParserRuleCall_0; }
		
		//Fichier
		public RuleCall getFichierParserRuleCall_1() { return cFichierParserRuleCall_1; }
		
		//Audio
		public RuleCall getAudioParserRuleCall_2() { return cAudioParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class NiveauElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Niveau");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNiveauAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNiveauKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cUnorderedGroup_4.eContents().get(0);
		private final Keyword cPseudoKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cPseudoAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_4_0_1_0 = (RuleCall)cPseudoAssignment_4_0_1.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cUnorderedGroup_4.eContents().get(1);
		private final Keyword cResponsablesKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1_1 = (Keyword)cGroup_4_1.eContents().get(1);
		private final Assignment cResponsablesAssignment_4_1_2 = (Assignment)cGroup_4_1.eContents().get(2);
		private final CrossReference cResponsablesIntervenantCrossReference_4_1_2_0 = (CrossReference)cResponsablesAssignment_4_1_2.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_1_2_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_1_2_0.eContents().get(1);
		private final Group cGroup_4_1_3 = (Group)cGroup_4_1.eContents().get(3);
		private final Keyword cCommaKeyword_4_1_3_0 = (Keyword)cGroup_4_1_3.eContents().get(0);
		private final Assignment cResponsablesAssignment_4_1_3_1 = (Assignment)cGroup_4_1_3.eContents().get(1);
		private final CrossReference cResponsablesIntervenantCrossReference_4_1_3_1_0 = (CrossReference)cResponsablesAssignment_4_1_3_1.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_1_3_1_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_1_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_1_4 = (Keyword)cGroup_4_1.eContents().get(4);
		private final Assignment cPresentationAssignment_4_2 = (Assignment)cUnorderedGroup_4.eContents().get(2);
		private final RuleCall cPresentationPresentationParserRuleCall_4_2_0 = (RuleCall)cPresentationAssignment_4_2.eContents().get(0);
		private final Alternatives cAlternatives_4_3 = (Alternatives)cUnorderedGroup_4.eContents().get(3);
		private final Assignment cFormationsAssignment_4_3_0 = (Assignment)cAlternatives_4_3.eContents().get(0);
		private final RuleCall cFormationsFormationParserRuleCall_4_3_0_0 = (RuleCall)cFormationsAssignment_4_3_0.eContents().get(0);
		private final Assignment cUesAssignment_4_3_1 = (Assignment)cAlternatives_4_3.eContents().get(1);
		private final RuleCall cUesUEParserRuleCall_4_3_1_0 = (RuleCall)cUesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Niveau returns Niveau:
		//    {Niveau}
		//    'Niveau'
		//    name=EString
		//    '{'
		//        (('pseudo' pseudo=EString)
		//        & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//        & (presentation=Presentation)?
		//        & (formations+=Formation | ues+=UE )*)
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Niveau}
		//'Niveau'
		//name=EString
		//'{'
		//    (('pseudo' pseudo=EString)
		//    & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//    & (presentation=Presentation)?
		//    & (formations+=Formation | ues+=UE )*)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Niveau}
		public Action getNiveauAction_0() { return cNiveauAction_0; }
		
		//'Niveau'
		public Keyword getNiveauKeyword_1() { return cNiveauKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(('pseudo' pseudo=EString)
		//& ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//& (presentation=Presentation)?
		//& (formations+=Formation | ues+=UE )*)
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }
		
		//('pseudo' pseudo=EString)
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_4_0_0() { return cPseudoKeyword_4_0_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_4_0_1() { return cPseudoAssignment_4_0_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_4_0_1_0() { return cPseudoEStringParserRuleCall_4_0_1_0; }
		
		//('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//'responsables'
		public Keyword getResponsablesKeyword_4_1_0() { return cResponsablesKeyword_4_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1_1() { return cLeftParenthesisKeyword_4_1_1; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_1_2() { return cResponsablesAssignment_4_1_2; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_1_2_0() { return cResponsablesIntervenantCrossReference_4_1_2_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_1_2_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_1_2_0_1; }
		
		//( "," responsables+=[Intervenant|EString])*
		public Group getGroup_4_1_3() { return cGroup_4_1_3; }
		
		//","
		public Keyword getCommaKeyword_4_1_3_0() { return cCommaKeyword_4_1_3_0; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_1_3_1() { return cResponsablesAssignment_4_1_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_1_3_1_0() { return cResponsablesIntervenantCrossReference_4_1_3_1_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_1_3_1_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_1_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_1_4() { return cRightParenthesisKeyword_4_1_4; }
		
		//(presentation=Presentation)?
		public Assignment getPresentationAssignment_4_2() { return cPresentationAssignment_4_2; }
		
		//Presentation
		public RuleCall getPresentationPresentationParserRuleCall_4_2_0() { return cPresentationPresentationParserRuleCall_4_2_0; }
		
		//(formations+=Formation | ues+=UE )*
		public Alternatives getAlternatives_4_3() { return cAlternatives_4_3; }
		
		//formations+=Formation
		public Assignment getFormationsAssignment_4_3_0() { return cFormationsAssignment_4_3_0; }
		
		//Formation
		public RuleCall getFormationsFormationParserRuleCall_4_3_0_0() { return cFormationsFormationParserRuleCall_4_3_0_0; }
		
		//ues+=UE
		public Assignment getUesAssignment_4_3_1() { return cUesAssignment_4_3_1; }
		
		//UE
		public RuleCall getUesUEParserRuleCall_4_3_1_0() { return cUesUEParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class IntervenantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Intervenant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntervenantAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntervenantKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPrenomKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPrenomAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPrenomEStringParserRuleCall_4_1_0 = (RuleCall)cPrenomAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Intervenant returns Intervenant:
		//    {Intervenant}
		//    'Intervenant'
		//    name=EString
		//    '{'
		//        ('prenom' prenom=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Intervenant}
		//'Intervenant'
		//name=EString
		//'{'
		//    ('prenom' prenom=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Intervenant}
		public Action getIntervenantAction_0() { return cIntervenantAction_0; }
		
		//'Intervenant'
		public Keyword getIntervenantKeyword_1() { return cIntervenantKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('prenom' prenom=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'prenom'
		public Keyword getPrenomKeyword_4_0() { return cPrenomKeyword_4_0; }
		
		//prenom=EString
		public Assignment getPrenomAssignment_4_1() { return cPrenomAssignment_4_1; }
		
		//EString
		public RuleCall getPrenomEStringParserRuleCall_4_1_0() { return cPrenomEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FormationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Formation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFormationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFormationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cUnorderedGroup_4.eContents().get(0);
		private final Keyword cPseudoKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cPseudoAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_4_0_1_0 = (RuleCall)cPseudoAssignment_4_0_1.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cUnorderedGroup_4.eContents().get(1);
		private final Keyword cResponsablesKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1_1 = (Keyword)cGroup_4_1.eContents().get(1);
		private final Assignment cResponsablesAssignment_4_1_2 = (Assignment)cGroup_4_1.eContents().get(2);
		private final CrossReference cResponsablesIntervenantCrossReference_4_1_2_0 = (CrossReference)cResponsablesAssignment_4_1_2.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_1_2_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_1_2_0.eContents().get(1);
		private final Group cGroup_4_1_3 = (Group)cGroup_4_1.eContents().get(3);
		private final Keyword cCommaKeyword_4_1_3_0 = (Keyword)cGroup_4_1_3.eContents().get(0);
		private final Assignment cResponsablesAssignment_4_1_3_1 = (Assignment)cGroup_4_1_3.eContents().get(1);
		private final CrossReference cResponsablesIntervenantCrossReference_4_1_3_1_0 = (CrossReference)cResponsablesAssignment_4_1_3_1.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_1_3_1_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_1_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_1_4 = (Keyword)cGroup_4_1.eContents().get(4);
		private final Group cGroup_4_2 = (Group)cUnorderedGroup_4.eContents().get(2);
		private final Keyword cEnseignantsKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_2_1 = (Keyword)cGroup_4_2.eContents().get(1);
		private final Assignment cEnseignantsAssignment_4_2_2 = (Assignment)cGroup_4_2.eContents().get(2);
		private final CrossReference cEnseignantsIntervenantCrossReference_4_2_2_0 = (CrossReference)cEnseignantsAssignment_4_2_2.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_4_2_2_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_4_2_2_0.eContents().get(1);
		private final Group cGroup_4_2_3 = (Group)cGroup_4_2.eContents().get(3);
		private final Keyword cCommaKeyword_4_2_3_0 = (Keyword)cGroup_4_2_3.eContents().get(0);
		private final Assignment cEnseignantsAssignment_4_2_3_1 = (Assignment)cGroup_4_2_3.eContents().get(1);
		private final CrossReference cEnseignantsIntervenantCrossReference_4_2_3_1_0 = (CrossReference)cEnseignantsAssignment_4_2_3_1.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_4_2_3_1_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_4_2_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_2_4 = (Keyword)cGroup_4_2.eContents().get(4);
		private final Assignment cPresentationAssignment_4_3 = (Assignment)cUnorderedGroup_4.eContents().get(3);
		private final RuleCall cPresentationPresentationParserRuleCall_4_3_0 = (RuleCall)cPresentationAssignment_4_3.eContents().get(0);
		private final Assignment cS1Assignment_4_4 = (Assignment)cUnorderedGroup_4.eContents().get(4);
		private final RuleCall cS1S1ParserRuleCall_4_4_0 = (RuleCall)cS1Assignment_4_4.eContents().get(0);
		private final Assignment cS2Assignment_4_5 = (Assignment)cUnorderedGroup_4.eContents().get(5);
		private final RuleCall cS2S2ParserRuleCall_4_5_0 = (RuleCall)cS2Assignment_4_5.eContents().get(0);
		private final Assignment cDocumentsAssignment_4_6 = (Assignment)cUnorderedGroup_4.eContents().get(6);
		private final RuleCall cDocumentsDocumentParserRuleCall_4_6_0 = (RuleCall)cDocumentsAssignment_4_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Formation returns Formation:
		//    {Formation}
		//    'Formation'
		//    name=EString
		//    '{'
		//        (('pseudo' pseudo=EString)
		//        & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//        & ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//        & (presentation=Presentation)?
		//        & s1=S1
		//        & s2=S2
		//        & (documents+=Document)*)
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Formation}
		//'Formation'
		//name=EString
		//'{'
		//    (('pseudo' pseudo=EString)
		//    & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//    & ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//    & (presentation=Presentation)?
		//    & s1=S1
		//    & s2=S2
		//    & (documents+=Document)*)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Formation}
		public Action getFormationAction_0() { return cFormationAction_0; }
		
		//'Formation'
		public Keyword getFormationKeyword_1() { return cFormationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(('pseudo' pseudo=EString)
		//& ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//& ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//& (presentation=Presentation)?
		//& s1=S1
		//& s2=S2
		//& (documents+=Document)*)
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }
		
		//('pseudo' pseudo=EString)
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_4_0_0() { return cPseudoKeyword_4_0_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_4_0_1() { return cPseudoAssignment_4_0_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_4_0_1_0() { return cPseudoEStringParserRuleCall_4_0_1_0; }
		
		//('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//'responsables'
		public Keyword getResponsablesKeyword_4_1_0() { return cResponsablesKeyword_4_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1_1() { return cLeftParenthesisKeyword_4_1_1; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_1_2() { return cResponsablesAssignment_4_1_2; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_1_2_0() { return cResponsablesIntervenantCrossReference_4_1_2_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_1_2_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_1_2_0_1; }
		
		//( "," responsables+=[Intervenant|EString])*
		public Group getGroup_4_1_3() { return cGroup_4_1_3; }
		
		//","
		public Keyword getCommaKeyword_4_1_3_0() { return cCommaKeyword_4_1_3_0; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_1_3_1() { return cResponsablesAssignment_4_1_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_1_3_1_0() { return cResponsablesIntervenantCrossReference_4_1_3_1_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_1_3_1_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_1_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_1_4() { return cRightParenthesisKeyword_4_1_4; }
		
		//('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//'enseignants'
		public Keyword getEnseignantsKeyword_4_2_0() { return cEnseignantsKeyword_4_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_2_1() { return cLeftParenthesisKeyword_4_2_1; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_4_2_2() { return cEnseignantsAssignment_4_2_2; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_4_2_2_0() { return cEnseignantsIntervenantCrossReference_4_2_2_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_4_2_2_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_4_2_2_0_1; }
		
		//( "," enseignants+=[Intervenant|EString])*
		public Group getGroup_4_2_3() { return cGroup_4_2_3; }
		
		//","
		public Keyword getCommaKeyword_4_2_3_0() { return cCommaKeyword_4_2_3_0; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_4_2_3_1() { return cEnseignantsAssignment_4_2_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_4_2_3_1_0() { return cEnseignantsIntervenantCrossReference_4_2_3_1_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_4_2_3_1_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_4_2_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_2_4() { return cRightParenthesisKeyword_4_2_4; }
		
		//(presentation=Presentation)?
		public Assignment getPresentationAssignment_4_3() { return cPresentationAssignment_4_3; }
		
		//Presentation
		public RuleCall getPresentationPresentationParserRuleCall_4_3_0() { return cPresentationPresentationParserRuleCall_4_3_0; }
		
		//s1=S1
		public Assignment getS1Assignment_4_4() { return cS1Assignment_4_4; }
		
		//S1
		public RuleCall getS1S1ParserRuleCall_4_4_0() { return cS1S1ParserRuleCall_4_4_0; }
		
		//s2=S2
		public Assignment getS2Assignment_4_5() { return cS2Assignment_4_5; }
		
		//S2
		public RuleCall getS2S2ParserRuleCall_4_5_0() { return cS2S2ParserRuleCall_4_5_0; }
		
		//(documents+=Document)*
		public Assignment getDocumentsAssignment_4_6() { return cDocumentsAssignment_4_6; }
		
		//Document
		public RuleCall getDocumentsDocumentParserRuleCall_4_6_0() { return cDocumentsDocumentParserRuleCall_4_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class PresentationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Presentation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPresentationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPresentationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cContenueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cContenueEStringParserRuleCall_2_0 = (RuleCall)cContenueAssignment_2.eContents().get(0);
		
		//Presentation returns Presentation:
		//    {Presentation}
		//    'Presentation' contenue=EString
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Presentation}
		//'Presentation' contenue=EString
		public Group getGroup() { return cGroup; }
		
		//{Presentation}
		public Action getPresentationAction_0() { return cPresentationAction_0; }
		
		//'Presentation'
		public Keyword getPresentationKeyword_1() { return cPresentationKeyword_1; }
		
		//contenue=EString
		public Assignment getContenueAssignment_2() { return cContenueAssignment_2; }
		
		//EString
		public RuleCall getContenueEStringParserRuleCall_2_0() { return cContenueEStringParserRuleCall_2_0; }
	}
	public class UEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.UE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUEAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cUnorderedGroup_4.eContents().get(0);
		private final Keyword cPseudoKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cPseudoAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_4_0_1_0 = (RuleCall)cPseudoAssignment_4_0_1.eContents().get(0);
		private final Assignment cPresentationAssignment_4_1 = (Assignment)cUnorderedGroup_4.eContents().get(1);
		private final RuleCall cPresentationPresentationParserRuleCall_4_1_0 = (RuleCall)cPresentationAssignment_4_1.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cUnorderedGroup_4.eContents().get(2);
		private final Keyword cResponsablesKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_2_1 = (Keyword)cGroup_4_2.eContents().get(1);
		private final Assignment cResponsablesAssignment_4_2_2 = (Assignment)cGroup_4_2.eContents().get(2);
		private final CrossReference cResponsablesIntervenantCrossReference_4_2_2_0 = (CrossReference)cResponsablesAssignment_4_2_2.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_2_2_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_2_2_0.eContents().get(1);
		private final Group cGroup_4_2_3 = (Group)cGroup_4_2.eContents().get(3);
		private final Keyword cCommaKeyword_4_2_3_0 = (Keyword)cGroup_4_2_3.eContents().get(0);
		private final Assignment cResponsablesAssignment_4_2_3_1 = (Assignment)cGroup_4_2_3.eContents().get(1);
		private final CrossReference cResponsablesIntervenantCrossReference_4_2_3_1_0 = (CrossReference)cResponsablesAssignment_4_2_3_1.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_2_3_1_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_2_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_2_4 = (Keyword)cGroup_4_2.eContents().get(4);
		private final Group cGroup_4_3 = (Group)cUnorderedGroup_4.eContents().get(3);
		private final Keyword cEnseignantsKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_3_1 = (Keyword)cGroup_4_3.eContents().get(1);
		private final Assignment cEnseignantsAssignment_4_3_2 = (Assignment)cGroup_4_3.eContents().get(2);
		private final CrossReference cEnseignantsIntervenantCrossReference_4_3_2_0 = (CrossReference)cEnseignantsAssignment_4_3_2.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_4_3_2_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_4_3_2_0.eContents().get(1);
		private final Group cGroup_4_3_3 = (Group)cGroup_4_3.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_3_0 = (Keyword)cGroup_4_3_3.eContents().get(0);
		private final Assignment cEnseignantsAssignment_4_3_3_1 = (Assignment)cGroup_4_3_3.eContents().get(1);
		private final CrossReference cEnseignantsIntervenantCrossReference_4_3_3_1_0 = (CrossReference)cEnseignantsAssignment_4_3_3_1.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_4_3_3_1_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_4_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_3_4 = (Keyword)cGroup_4_3.eContents().get(4);
		private final Assignment cDocumentsAssignment_4_4 = (Assignment)cUnorderedGroup_4.eContents().get(4);
		private final RuleCall cDocumentsDocumentParserRuleCall_4_4_0 = (RuleCall)cDocumentsAssignment_4_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//UE returns UE:
		//    {UE}
		//    'UE'
		//    name=EString
		//    '{'
		//        (('pseudo' pseudo=EString)
		//        & (presentation=Presentation)?
		//        & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//        & ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//        & (documents+=Document)*)
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{UE}
		//'UE'
		//name=EString
		//'{'
		//    (('pseudo' pseudo=EString)
		//    & (presentation=Presentation)?
		//    & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//    & ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//    & (documents+=Document)*)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{UE}
		public Action getUEAction_0() { return cUEAction_0; }
		
		//'UE'
		public Keyword getUEKeyword_1() { return cUEKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(('pseudo' pseudo=EString)
		//& (presentation=Presentation)?
		//& ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//& ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//& (documents+=Document)*)
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }
		
		//('pseudo' pseudo=EString)
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_4_0_0() { return cPseudoKeyword_4_0_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_4_0_1() { return cPseudoAssignment_4_0_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_4_0_1_0() { return cPseudoEStringParserRuleCall_4_0_1_0; }
		
		//(presentation=Presentation)?
		public Assignment getPresentationAssignment_4_1() { return cPresentationAssignment_4_1; }
		
		//Presentation
		public RuleCall getPresentationPresentationParserRuleCall_4_1_0() { return cPresentationPresentationParserRuleCall_4_1_0; }
		
		//('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//'responsables'
		public Keyword getResponsablesKeyword_4_2_0() { return cResponsablesKeyword_4_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_2_1() { return cLeftParenthesisKeyword_4_2_1; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_2_2() { return cResponsablesAssignment_4_2_2; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_2_2_0() { return cResponsablesIntervenantCrossReference_4_2_2_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_2_2_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_2_2_0_1; }
		
		//( "," responsables+=[Intervenant|EString])*
		public Group getGroup_4_2_3() { return cGroup_4_2_3; }
		
		//","
		public Keyword getCommaKeyword_4_2_3_0() { return cCommaKeyword_4_2_3_0; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_2_3_1() { return cResponsablesAssignment_4_2_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_2_3_1_0() { return cResponsablesIntervenantCrossReference_4_2_3_1_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_2_3_1_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_2_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_2_4() { return cRightParenthesisKeyword_4_2_4; }
		
		//('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//'enseignants'
		public Keyword getEnseignantsKeyword_4_3_0() { return cEnseignantsKeyword_4_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_3_1() { return cLeftParenthesisKeyword_4_3_1; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_4_3_2() { return cEnseignantsAssignment_4_3_2; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_4_3_2_0() { return cEnseignantsIntervenantCrossReference_4_3_2_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_4_3_2_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_4_3_2_0_1; }
		
		//( "," enseignants+=[Intervenant|EString])*
		public Group getGroup_4_3_3() { return cGroup_4_3_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_3_0() { return cCommaKeyword_4_3_3_0; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_4_3_3_1() { return cEnseignantsAssignment_4_3_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_4_3_3_1_0() { return cEnseignantsIntervenantCrossReference_4_3_3_1_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_4_3_3_1_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_4_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_3_4() { return cRightParenthesisKeyword_4_3_4; }
		
		//(documents+=Document)*
		public Assignment getDocumentsAssignment_4_4() { return cDocumentsAssignment_4_4; }
		
		//Document
		public RuleCall getDocumentsDocumentParserRuleCall_4_4_0() { return cDocumentsDocumentParserRuleCall_4_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class S1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.S1");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cS1Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cS1Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cUesoptionnellesKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Assignment cUesoptionnellesAssignment_3_0_2 = (Assignment)cGroup_3_0.eContents().get(2);
		private final CrossReference cUesoptionnellesUECrossReference_3_0_2_0 = (CrossReference)cUesoptionnellesAssignment_3_0_2.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_0_2_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_0_2_0.eContents().get(1);
		private final Group cGroup_3_0_3 = (Group)cGroup_3_0.eContents().get(3);
		private final Keyword cCommaKeyword_3_0_3_0 = (Keyword)cGroup_3_0_3.eContents().get(0);
		private final Assignment cUesoptionnellesAssignment_3_0_3_1 = (Assignment)cGroup_3_0_3.eContents().get(1);
		private final CrossReference cUesoptionnellesUECrossReference_3_0_3_1_0 = (CrossReference)cUesoptionnellesAssignment_3_0_3_1.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_0_3_1_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_0_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_0_4 = (Keyword)cGroup_3_0.eContents().get(4);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cUesobligatoiresKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Assignment cUesobligatoiresAssignment_3_1_2 = (Assignment)cGroup_3_1.eContents().get(2);
		private final CrossReference cUesobligatoiresUECrossReference_3_1_2_0 = (CrossReference)cUesobligatoiresAssignment_3_1_2.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_3_1_2_0_1 = (RuleCall)cUesobligatoiresUECrossReference_3_1_2_0.eContents().get(1);
		private final Group cGroup_3_1_3 = (Group)cGroup_3_1.eContents().get(3);
		private final Keyword cCommaKeyword_3_1_3_0 = (Keyword)cGroup_3_1_3.eContents().get(0);
		private final Assignment cUesobligatoiresAssignment_3_1_3_1 = (Assignment)cGroup_3_1_3.eContents().get(1);
		private final CrossReference cUesobligatoiresUECrossReference_3_1_3_1_0 = (CrossReference)cUesobligatoiresAssignment_3_1_3_1.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_3_1_3_1_0_1 = (RuleCall)cUesobligatoiresUECrossReference_3_1_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_1_4 = (Keyword)cGroup_3_1.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//S1 returns S1:
		//    {S1}
		//    'S1'
		//    '{'
		//        (('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//        & ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{S1}
		//'S1'
		//'{'
		//    (('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//    & ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{S1}
		public Action getS1Action_0() { return cS1Action_0; }
		
		//'S1'
		public Keyword getS1Keyword_1() { return cS1Keyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//& ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }
		
		//('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'uesoptionnelles'
		public Keyword getUesoptionnellesKeyword_3_0_0() { return cUesoptionnellesKeyword_3_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0_1() { return cLeftParenthesisKeyword_3_0_1; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_0_2() { return cUesoptionnellesAssignment_3_0_2; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_0_2_0() { return cUesoptionnellesUECrossReference_3_0_2_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_0_2_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_0_2_0_1; }
		
		//( "," uesoptionnelles+=[UE|EString])*
		public Group getGroup_3_0_3() { return cGroup_3_0_3; }
		
		//","
		public Keyword getCommaKeyword_3_0_3_0() { return cCommaKeyword_3_0_3_0; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_0_3_1() { return cUesoptionnellesAssignment_3_0_3_1; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_0_3_1_0() { return cUesoptionnellesUECrossReference_3_0_3_1_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_0_3_1_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_0_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_0_4() { return cRightParenthesisKeyword_3_0_4; }
		
		//('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'uesobligatoires'
		public Keyword getUesobligatoiresKeyword_3_1_0() { return cUesobligatoiresKeyword_3_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1_1() { return cLeftParenthesisKeyword_3_1_1; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_3_1_2() { return cUesobligatoiresAssignment_3_1_2; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_3_1_2_0() { return cUesobligatoiresUECrossReference_3_1_2_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_3_1_2_0_1() { return cUesobligatoiresUEEStringParserRuleCall_3_1_2_0_1; }
		
		//( "," uesobligatoires+=[UE|EString])*
		public Group getGroup_3_1_3() { return cGroup_3_1_3; }
		
		//","
		public Keyword getCommaKeyword_3_1_3_0() { return cCommaKeyword_3_1_3_0; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_3_1_3_1() { return cUesobligatoiresAssignment_3_1_3_1; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_3_1_3_1_0() { return cUesobligatoiresUECrossReference_3_1_3_1_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_3_1_3_1_0_1() { return cUesobligatoiresUEEStringParserRuleCall_3_1_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_1_4() { return cRightParenthesisKeyword_3_1_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class S2Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.S2");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cS2Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cS2Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cUesoptionnellesKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Assignment cUesoptionnellesAssignment_3_0_2 = (Assignment)cGroup_3_0.eContents().get(2);
		private final CrossReference cUesoptionnellesUECrossReference_3_0_2_0 = (CrossReference)cUesoptionnellesAssignment_3_0_2.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_0_2_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_0_2_0.eContents().get(1);
		private final Group cGroup_3_0_3 = (Group)cGroup_3_0.eContents().get(3);
		private final Keyword cCommaKeyword_3_0_3_0 = (Keyword)cGroup_3_0_3.eContents().get(0);
		private final Assignment cUesoptionnellesAssignment_3_0_3_1 = (Assignment)cGroup_3_0_3.eContents().get(1);
		private final CrossReference cUesoptionnellesUECrossReference_3_0_3_1_0 = (CrossReference)cUesoptionnellesAssignment_3_0_3_1.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_0_3_1_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_0_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_0_4 = (Keyword)cGroup_3_0.eContents().get(4);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cUesobligatoiresKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Assignment cUesobligatoiresAssignment_3_1_2 = (Assignment)cGroup_3_1.eContents().get(2);
		private final CrossReference cUesobligatoiresUECrossReference_3_1_2_0 = (CrossReference)cUesobligatoiresAssignment_3_1_2.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_3_1_2_0_1 = (RuleCall)cUesobligatoiresUECrossReference_3_1_2_0.eContents().get(1);
		private final Group cGroup_3_1_3 = (Group)cGroup_3_1.eContents().get(3);
		private final Keyword cCommaKeyword_3_1_3_0 = (Keyword)cGroup_3_1_3.eContents().get(0);
		private final Assignment cUesobligatoiresAssignment_3_1_3_1 = (Assignment)cGroup_3_1_3.eContents().get(1);
		private final CrossReference cUesobligatoiresUECrossReference_3_1_3_1_0 = (CrossReference)cUesobligatoiresAssignment_3_1_3_1.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_3_1_3_1_0_1 = (RuleCall)cUesobligatoiresUECrossReference_3_1_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_1_4 = (Keyword)cGroup_3_1.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//S2 returns S2:
		//    {S2}
		//    'S2'
		//    '{'
		//        (('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//        & ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{S2}
		//'S2'
		//'{'
		//    (('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//    & ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{S2}
		public Action getS2Action_0() { return cS2Action_0; }
		
		//'S2'
		public Keyword getS2Keyword_1() { return cS2Keyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//& ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }
		
		//('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'uesoptionnelles'
		public Keyword getUesoptionnellesKeyword_3_0_0() { return cUesoptionnellesKeyword_3_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0_1() { return cLeftParenthesisKeyword_3_0_1; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_0_2() { return cUesoptionnellesAssignment_3_0_2; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_0_2_0() { return cUesoptionnellesUECrossReference_3_0_2_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_0_2_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_0_2_0_1; }
		
		//( "," uesoptionnelles+=[UE|EString])*
		public Group getGroup_3_0_3() { return cGroup_3_0_3; }
		
		//","
		public Keyword getCommaKeyword_3_0_3_0() { return cCommaKeyword_3_0_3_0; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_0_3_1() { return cUesoptionnellesAssignment_3_0_3_1; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_0_3_1_0() { return cUesoptionnellesUECrossReference_3_0_3_1_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_0_3_1_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_0_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_0_4() { return cRightParenthesisKeyword_3_0_4; }
		
		//('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'uesobligatoires'
		public Keyword getUesobligatoiresKeyword_3_1_0() { return cUesobligatoiresKeyword_3_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1_1() { return cLeftParenthesisKeyword_3_1_1; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_3_1_2() { return cUesobligatoiresAssignment_3_1_2; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_3_1_2_0() { return cUesobligatoiresUECrossReference_3_1_2_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_3_1_2_0_1() { return cUesobligatoiresUEEStringParserRuleCall_3_1_2_0_1; }
		
		//( "," uesobligatoires+=[UE|EString])*
		public Group getGroup_3_1_3() { return cGroup_3_1_3; }
		
		//","
		public Keyword getCommaKeyword_3_1_3_0() { return cCommaKeyword_3_1_3_0; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_3_1_3_1() { return cUesobligatoiresAssignment_3_1_3_1; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_3_1_3_1_0() { return cUesobligatoiresUECrossReference_3_1_3_1_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_3_1_3_1_0_1() { return cUesobligatoiresUEEStringParserRuleCall_3_1_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_1_4() { return cRightParenthesisKeyword_3_1_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class VideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Video");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVideoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVideoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cLienKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLienAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLienEStringParserRuleCall_6_0 = (RuleCall)cLienAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDureeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDureeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cDureeEStringParserRuleCall_7_1_0 = (RuleCall)cDureeAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Video returns Video:
		//    {Video}
		//    'Video'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'lien' lien=EString
		//        ('duree' duree=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Video}
		//'Video'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'lien' lien=EString
		//    ('duree' duree=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Video}
		public Action getVideoAction_0() { return cVideoAction_0; }
		
		//'Video'
		public Keyword getVideoKeyword_1() { return cVideoKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'lien'
		public Keyword getLienKeyword_5() { return cLienKeyword_5; }
		
		//lien=EString
		public Assignment getLienAssignment_6() { return cLienAssignment_6; }
		
		//EString
		public RuleCall getLienEStringParserRuleCall_6_0() { return cLienEStringParserRuleCall_6_0; }
		
		//('duree' duree=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'duree'
		public Keyword getDureeKeyword_7_0() { return cDureeKeyword_7_0; }
		
		//duree=EString
		public Assignment getDureeAssignment_7_1() { return cDureeAssignment_7_1; }
		
		//EString
		public RuleCall getDureeEStringParserRuleCall_7_1_0() { return cDureeEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class FichierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Fichier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFichierAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFichierKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cLienKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLienAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLienEStringParserRuleCall_6_0 = (RuleCall)cLienAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAuteurKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAuteurAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAuteurEStringParserRuleCall_7_1_0 = (RuleCall)cAuteurAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Fichier returns Fichier:
		//    {Fichier}
		//    'Fichier'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'lien' lien=EString
		//        ('auteur' auteur=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Fichier}
		//'Fichier'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'lien' lien=EString
		//    ('auteur' auteur=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Fichier}
		public Action getFichierAction_0() { return cFichierAction_0; }
		
		//'Fichier'
		public Keyword getFichierKeyword_1() { return cFichierKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'lien'
		public Keyword getLienKeyword_5() { return cLienKeyword_5; }
		
		//lien=EString
		public Assignment getLienAssignment_6() { return cLienAssignment_6; }
		
		//EString
		public RuleCall getLienEStringParserRuleCall_6_0() { return cLienEStringParserRuleCall_6_0; }
		
		//('auteur' auteur=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'auteur'
		public Keyword getAuteurKeyword_7_0() { return cAuteurKeyword_7_0; }
		
		//auteur=EString
		public Assignment getAuteurAssignment_7_1() { return cAuteurAssignment_7_1; }
		
		//EString
		public RuleCall getAuteurEStringParserRuleCall_7_1_0() { return cAuteurEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class AudioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Audio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAudioAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAudioKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cLienKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLienAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLienEStringParserRuleCall_6_0 = (RuleCall)cLienAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDureeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDureeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cDureeEStringParserRuleCall_7_1_0 = (RuleCall)cDureeAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Audio returns Audio:
		//    {Audio}
		//    'Audio'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'lien' lien=EString
		//        ('duree' duree=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Audio}
		//'Audio'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'lien' lien=EString
		//    ('duree' duree=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Audio}
		public Action getAudioAction_0() { return cAudioAction_0; }
		
		//'Audio'
		public Keyword getAudioKeyword_1() { return cAudioKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'lien'
		public Keyword getLienKeyword_5() { return cLienKeyword_5; }
		
		//lien=EString
		public Assignment getLienAssignment_6() { return cLienAssignment_6; }
		
		//EString
		public RuleCall getLienEStringParserRuleCall_6_0() { return cLienEStringParserRuleCall_6_0; }
		
		//('duree' duree=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'duree'
		public Keyword getDureeKeyword_7_0() { return cDureeKeyword_7_0; }
		
		//duree=EString
		public Assignment getDureeAssignment_7_1() { return cDureeAssignment_7_1; }
		
		//EString
		public RuleCall getDureeEStringParserRuleCall_7_1_0() { return cDureeEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	private final FaculteElements pFaculte;
	private final DocumentElements pDocument;
	private final EStringElements pEString;
	private final NiveauElements pNiveau;
	private final IntervenantElements pIntervenant;
	private final FormationElements pFormation;
	private final PresentationElements pPresentation;
	private final UEElements pUE;
	private final S1Elements pS1;
	private final S2Elements pS2;
	private final VideoElements pVideo;
	private final FichierElements pFichier;
	private final AudioElements pAudio;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LangFilGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFaculte = new FaculteElements();
		this.pDocument = new DocumentElements();
		this.pEString = new EStringElements();
		this.pNiveau = new NiveauElements();
		this.pIntervenant = new IntervenantElements();
		this.pFormation = new FormationElements();
		this.pPresentation = new PresentationElements();
		this.pUE = new UEElements();
		this.pS1 = new S1Elements();
		this.pS2 = new S2Elements();
		this.pVideo = new VideoElements();
		this.pFichier = new FichierElements();
		this.pAudio = new AudioElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fil.xtext.LangFil".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Faculte returns Faculte:
	//    {Faculte}
	//    'Faculte'
	//    name=EString
	//        (niveaux+=Niveau | intervenants+=Intervenant)*
	//    ;
	public FaculteElements getFaculteAccess() {
		return pFaculte;
	}
	
	public ParserRule getFaculteRule() {
		return getFaculteAccess().getRule();
	}
	
	//Document returns Document:
	//    Video | Fichier | Audio;
	public DocumentElements getDocumentAccess() {
		return pDocument;
	}
	
	public ParserRule getDocumentRule() {
		return getDocumentAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Niveau returns Niveau:
	//    {Niveau}
	//    'Niveau'
	//    name=EString
	//    '{'
	//        (('pseudo' pseudo=EString)
	//        & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
	//        & (presentation=Presentation)?
	//        & (formations+=Formation | ues+=UE )*)
	//    '}';
	public NiveauElements getNiveauAccess() {
		return pNiveau;
	}
	
	public ParserRule getNiveauRule() {
		return getNiveauAccess().getRule();
	}
	
	//Intervenant returns Intervenant:
	//    {Intervenant}
	//    'Intervenant'
	//    name=EString
	//    '{'
	//        ('prenom' prenom=EString)?
	//    '}';
	public IntervenantElements getIntervenantAccess() {
		return pIntervenant;
	}
	
	public ParserRule getIntervenantRule() {
		return getIntervenantAccess().getRule();
	}
	
	//Formation returns Formation:
	//    {Formation}
	//    'Formation'
	//    name=EString
	//    '{'
	//        (('pseudo' pseudo=EString)
	//        & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
	//        & ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
	//        & (presentation=Presentation)?
	//        & s1=S1
	//        & s2=S2
	//        & (documents+=Document)*)
	//    '}';
	public FormationElements getFormationAccess() {
		return pFormation;
	}
	
	public ParserRule getFormationRule() {
		return getFormationAccess().getRule();
	}
	
	//Presentation returns Presentation:
	//    {Presentation}
	//    'Presentation' contenue=EString
	//    ;
	public PresentationElements getPresentationAccess() {
		return pPresentation;
	}
	
	public ParserRule getPresentationRule() {
		return getPresentationAccess().getRule();
	}
	
	//UE returns UE:
	//    {UE}
	//    'UE'
	//    name=EString
	//    '{'
	//        (('pseudo' pseudo=EString)
	//        & (presentation=Presentation)?
	//        & ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
	//        & ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
	//        & (documents+=Document)*)
	//    '}';
	public UEElements getUEAccess() {
		return pUE;
	}
	
	public ParserRule getUERule() {
		return getUEAccess().getRule();
	}
	
	//S1 returns S1:
	//    {S1}
	//    'S1'
	//    '{'
	//        (('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
	//        & ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
	//    '}';
	public S1Elements getS1Access() {
		return pS1;
	}
	
	public ParserRule getS1Rule() {
		return getS1Access().getRule();
	}
	
	//S2 returns S2:
	//    {S2}
	//    'S2'
	//    '{'
	//        (('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
	//        & ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?)
	//    '}';
	public S2Elements getS2Access() {
		return pS2;
	}
	
	public ParserRule getS2Rule() {
		return getS2Access().getRule();
	}
	
	//Video returns Video:
	//    {Video}
	//    'Video'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'lien' lien=EString
	//        ('duree' duree=EString)?
	//    '}';
	public VideoElements getVideoAccess() {
		return pVideo;
	}
	
	public ParserRule getVideoRule() {
		return getVideoAccess().getRule();
	}
	
	//Fichier returns Fichier:
	//    {Fichier}
	//    'Fichier'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'lien' lien=EString
	//        ('auteur' auteur=EString)?
	//    '}';
	public FichierElements getFichierAccess() {
		return pFichier;
	}
	
	public ParserRule getFichierRule() {
		return getFichierAccess().getRule();
	}
	
	//Audio returns Audio:
	//    {Audio}
	//    'Audio'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'lien' lien=EString
	//        ('duree' duree=EString)?
	//    '}';
	public AudioElements getAudioAccess() {
		return pAudio;
	}
	
	public ParserRule getAudioRule() {
		return getAudioAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
