/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LangFilGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class FaculteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Faculte");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFaculteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFaculteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNiveauxKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cNiveauxAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cNiveauxNiveauParserRuleCall_4_2_0 = (RuleCall)cNiveauxAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cNiveauxAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cNiveauxNiveauParserRuleCall_4_3_1_0 = (RuleCall)cNiveauxAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIntervenantsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cIntervenantsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cIntervenantsIntervenantParserRuleCall_5_2_0 = (RuleCall)cIntervenantsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cIntervenantsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cIntervenantsIntervenantParserRuleCall_5_3_1_0 = (RuleCall)cIntervenantsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Faculte returns Faculte:
		//    {Faculte}
		//    'Faculte'
		//    name=EString
		//    '{'
		//        ('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}' )?
		//        ('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Faculte}
		//'Faculte'
		//name=EString
		//'{'
		//    ('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}' )?
		//    ('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Faculte}
		public Action getFaculteAction_0() { return cFaculteAction_0; }
		
		//'Faculte'
		public Keyword getFaculteKeyword_1() { return cFaculteKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'niveaux'
		public Keyword getNiveauxKeyword_4_0() { return cNiveauxKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//niveaux+=Niveau
		public Assignment getNiveauxAssignment_4_2() { return cNiveauxAssignment_4_2; }
		
		//Niveau
		public RuleCall getNiveauxNiveauParserRuleCall_4_2_0() { return cNiveauxNiveauParserRuleCall_4_2_0; }
		
		//( "," niveaux+=Niveau)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//niveaux+=Niveau
		public Assignment getNiveauxAssignment_4_3_1() { return cNiveauxAssignment_4_3_1; }
		
		//Niveau
		public RuleCall getNiveauxNiveauParserRuleCall_4_3_1_0() { return cNiveauxNiveauParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'intervenants'
		public Keyword getIntervenantsKeyword_5_0() { return cIntervenantsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//intervenants+=Intervenant
		public Assignment getIntervenantsAssignment_5_2() { return cIntervenantsAssignment_5_2; }
		
		//Intervenant
		public RuleCall getIntervenantsIntervenantParserRuleCall_5_2_0() { return cIntervenantsIntervenantParserRuleCall_5_2_0; }
		
		//( "," intervenants+=Intervenant)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//intervenants+=Intervenant
		public Assignment getIntervenantsAssignment_5_3_1() { return cIntervenantsAssignment_5_3_1; }
		
		//Intervenant
		public RuleCall getIntervenantsIntervenantParserRuleCall_5_3_1_0() { return cIntervenantsIntervenantParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class DocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Document");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVideoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFichierParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAudioParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Document returns Document:
		//    Video | Fichier | Audio;
		@Override public ParserRule getRule() { return rule; }
		
		//Video | Fichier | Audio
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Video
		public RuleCall getVideoParserRuleCall_0() { return cVideoParserRuleCall_0; }
		
		//Fichier
		public RuleCall getFichierParserRuleCall_1() { return cFichierParserRuleCall_1; }
		
		//Audio
		public RuleCall getAudioParserRuleCall_2() { return cAudioParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class NiveauElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Niveau");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNiveauAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNiveauKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPseudoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPseudoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_4_1_0 = (RuleCall)cPseudoAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResponsablesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cResponsablesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cResponsablesIntervenantCrossReference_5_2_0 = (CrossReference)cResponsablesAssignment_5_2.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_5_2_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cResponsablesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cResponsablesIntervenantCrossReference_5_3_1_0 = (CrossReference)cResponsablesAssignment_5_3_1.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cFormationsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cFormationsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cFormationsFormationParserRuleCall_6_2_0 = (RuleCall)cFormationsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cFormationsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cFormationsFormationParserRuleCall_6_3_1_0 = (RuleCall)cFormationsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPresentationKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPresentationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPresentationPresentationParserRuleCall_7_1_0 = (RuleCall)cPresentationAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cUesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cUesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cUesUEParserRuleCall_8_2_0 = (RuleCall)cUesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cUesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cUesUEParserRuleCall_8_3_1_0 = (RuleCall)cUesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Niveau returns Niveau:
		//    {Niveau}
		//    'Niveau'
		//    name=EString
		//    '{'
		//        ('pseudo' pseudo=EString)?
		//        ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//        ('formations' '{' formations+=Formation ( "," formations+=Formation)* '}' )?
		//        ('presentation' presentation=Presentation)?
		//        ('ues' '{' ues+=UE ( "," ues+=UE)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Niveau}
		//'Niveau'
		//name=EString
		//'{'
		//    ('pseudo' pseudo=EString)?
		//    ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//    ('formations' '{' formations+=Formation ( "," formations+=Formation)* '}' )?
		//    ('presentation' presentation=Presentation)?
		//    ('ues' '{' ues+=UE ( "," ues+=UE)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Niveau}
		public Action getNiveauAction_0() { return cNiveauAction_0; }
		
		//'Niveau'
		public Keyword getNiveauKeyword_1() { return cNiveauKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('pseudo' pseudo=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_4_0() { return cPseudoKeyword_4_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_4_1() { return cPseudoAssignment_4_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_4_1_0() { return cPseudoEStringParserRuleCall_4_1_0; }
		
		//('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'responsables'
		public Keyword getResponsablesKeyword_5_0() { return cResponsablesKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_5_2() { return cResponsablesAssignment_5_2; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_5_2_0() { return cResponsablesIntervenantCrossReference_5_2_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_5_2_0_1() { return cResponsablesIntervenantEStringParserRuleCall_5_2_0_1; }
		
		//( "," responsables+=[Intervenant|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_5_3_1() { return cResponsablesAssignment_5_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_5_3_1_0() { return cResponsablesIntervenantCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_5_3_1_0_1() { return cResponsablesIntervenantEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('formations' '{' formations+=Formation ( "," formations+=Formation)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'formations'
		public Keyword getFormationsKeyword_6_0() { return cFormationsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//formations+=Formation
		public Assignment getFormationsAssignment_6_2() { return cFormationsAssignment_6_2; }
		
		//Formation
		public RuleCall getFormationsFormationParserRuleCall_6_2_0() { return cFormationsFormationParserRuleCall_6_2_0; }
		
		//( "," formations+=Formation)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//formations+=Formation
		public Assignment getFormationsAssignment_6_3_1() { return cFormationsAssignment_6_3_1; }
		
		//Formation
		public RuleCall getFormationsFormationParserRuleCall_6_3_1_0() { return cFormationsFormationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('presentation' presentation=Presentation)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'presentation'
		public Keyword getPresentationKeyword_7_0() { return cPresentationKeyword_7_0; }
		
		//presentation=Presentation
		public Assignment getPresentationAssignment_7_1() { return cPresentationAssignment_7_1; }
		
		//Presentation
		public RuleCall getPresentationPresentationParserRuleCall_7_1_0() { return cPresentationPresentationParserRuleCall_7_1_0; }
		
		//('ues' '{' ues+=UE ( "," ues+=UE)* '}' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'ues'
		public Keyword getUesKeyword_8_0() { return cUesKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//ues+=UE
		public Assignment getUesAssignment_8_2() { return cUesAssignment_8_2; }
		
		//UE
		public RuleCall getUesUEParserRuleCall_8_2_0() { return cUesUEParserRuleCall_8_2_0; }
		
		//( "," ues+=UE)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//ues+=UE
		public Assignment getUesAssignment_8_3_1() { return cUesAssignment_8_3_1; }
		
		//UE
		public RuleCall getUesUEParserRuleCall_8_3_1_0() { return cUesUEParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class IntervenantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Intervenant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntervenantAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntervenantKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPrenomKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPrenomAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPrenomEStringParserRuleCall_4_1_0 = (RuleCall)cPrenomAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Intervenant returns Intervenant:
		//    {Intervenant}
		//    'Intervenant'
		//    name=EString
		//    '{'
		//        ('prenom' prenom=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Intervenant}
		//'Intervenant'
		//name=EString
		//'{'
		//    ('prenom' prenom=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Intervenant}
		public Action getIntervenantAction_0() { return cIntervenantAction_0; }
		
		//'Intervenant'
		public Keyword getIntervenantKeyword_1() { return cIntervenantKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('prenom' prenom=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'prenom'
		public Keyword getPrenomKeyword_4_0() { return cPrenomKeyword_4_0; }
		
		//prenom=EString
		public Assignment getPrenomAssignment_4_1() { return cPrenomAssignment_4_1; }
		
		//EString
		public RuleCall getPrenomEStringParserRuleCall_4_1_0() { return cPrenomEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FormationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Formation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFormationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPseudoKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPseudoAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_3_1_0 = (RuleCall)cPseudoAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResponsablesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cResponsablesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cResponsablesIntervenantCrossReference_4_2_0 = (CrossReference)cResponsablesAssignment_4_2.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_2_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cResponsablesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cResponsablesIntervenantCrossReference_4_3_1_0 = (CrossReference)cResponsablesAssignment_4_3_1.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEnseignantsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cEnseignantsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cEnseignantsIntervenantCrossReference_5_2_0 = (CrossReference)cEnseignantsAssignment_5_2.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_5_2_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cEnseignantsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cEnseignantsIntervenantCrossReference_5_3_1_0 = (CrossReference)cEnseignantsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPresentationKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPresentationAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPresentationPresentationParserRuleCall_6_1_0 = (RuleCall)cPresentationAssignment_6_1.eContents().get(0);
		private final Keyword cS1Keyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cS1Assignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cS1S1ParserRuleCall_8_0 = (RuleCall)cS1Assignment_8.eContents().get(0);
		private final Keyword cS2Keyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cS2Assignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cS2S2ParserRuleCall_10_0 = (RuleCall)cS2Assignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cDocumentsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cDocumentsAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cDocumentsDocumentParserRuleCall_11_2_0 = (RuleCall)cDocumentsAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cDocumentsAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cDocumentsDocumentParserRuleCall_11_3_1_0 = (RuleCall)cDocumentsAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Formation returns Formation:
		//    'Formation'
		//    name=EString
		//    '{'
		//        ('pseudo' pseudo=EString)?
		//        ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//        ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//        ('presentation' presentation=Presentation)?
		//        's1' s1=S1
		//        's2' s2=S2
		//        ('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Formation'
		//name=EString
		//'{'
		//    ('pseudo' pseudo=EString)?
		//    ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//    ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//    ('presentation' presentation=Presentation)?
		//    's1' s1=S1
		//    's2' s2=S2
		//    ('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Formation'
		public Keyword getFormationKeyword_0() { return cFormationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('pseudo' pseudo=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_3_0() { return cPseudoKeyword_3_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_3_1() { return cPseudoAssignment_3_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_3_1_0() { return cPseudoEStringParserRuleCall_3_1_0; }
		
		//('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'responsables'
		public Keyword getResponsablesKeyword_4_0() { return cResponsablesKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_2() { return cResponsablesAssignment_4_2; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_2_0() { return cResponsablesIntervenantCrossReference_4_2_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_2_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_2_0_1; }
		
		//( "," responsables+=[Intervenant|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_4_3_1() { return cResponsablesAssignment_4_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_4_3_1_0() { return cResponsablesIntervenantCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_4_3_1_0_1() { return cResponsablesIntervenantEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'enseignants'
		public Keyword getEnseignantsKeyword_5_0() { return cEnseignantsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_5_2() { return cEnseignantsAssignment_5_2; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_5_2_0() { return cEnseignantsIntervenantCrossReference_5_2_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_5_2_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_5_2_0_1; }
		
		//( "," enseignants+=[Intervenant|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_5_3_1() { return cEnseignantsAssignment_5_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_5_3_1_0() { return cEnseignantsIntervenantCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_5_3_1_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('presentation' presentation=Presentation)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'presentation'
		public Keyword getPresentationKeyword_6_0() { return cPresentationKeyword_6_0; }
		
		//presentation=Presentation
		public Assignment getPresentationAssignment_6_1() { return cPresentationAssignment_6_1; }
		
		//Presentation
		public RuleCall getPresentationPresentationParserRuleCall_6_1_0() { return cPresentationPresentationParserRuleCall_6_1_0; }
		
		//'s1'
		public Keyword getS1Keyword_7() { return cS1Keyword_7; }
		
		//s1=S1
		public Assignment getS1Assignment_8() { return cS1Assignment_8; }
		
		//S1
		public RuleCall getS1S1ParserRuleCall_8_0() { return cS1S1ParserRuleCall_8_0; }
		
		//'s2'
		public Keyword getS2Keyword_9() { return cS2Keyword_9; }
		
		//s2=S2
		public Assignment getS2Assignment_10() { return cS2Assignment_10; }
		
		//S2
		public RuleCall getS2S2ParserRuleCall_10_0() { return cS2S2ParserRuleCall_10_0; }
		
		//('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
		public Group getGroup_11() { return cGroup_11; }
		
		//'documents'
		public Keyword getDocumentsKeyword_11_0() { return cDocumentsKeyword_11_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }
		
		//documents+=Document
		public Assignment getDocumentsAssignment_11_2() { return cDocumentsAssignment_11_2; }
		
		//Document
		public RuleCall getDocumentsDocumentParserRuleCall_11_2_0() { return cDocumentsDocumentParserRuleCall_11_2_0; }
		
		//( "," documents+=Document)*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//documents+=Document
		public Assignment getDocumentsAssignment_11_3_1() { return cDocumentsAssignment_11_3_1; }
		
		//Document
		public RuleCall getDocumentsDocumentParserRuleCall_11_3_1_0() { return cDocumentsDocumentParserRuleCall_11_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class PresentationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Presentation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPresentationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPresentationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cContenueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cContenueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cContenueEStringParserRuleCall_3_1_0 = (RuleCall)cContenueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Presentation returns Presentation:
		//    {Presentation}
		//    'Presentation'
		//    '{'
		//        ('contenue' contenue=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Presentation}
		//'Presentation'
		//'{'
		//    ('contenue' contenue=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Presentation}
		public Action getPresentationAction_0() { return cPresentationAction_0; }
		
		//'Presentation'
		public Keyword getPresentationKeyword_1() { return cPresentationKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('contenue' contenue=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'contenue'
		public Keyword getContenueKeyword_3_0() { return cContenueKeyword_3_0; }
		
		//contenue=EString
		public Assignment getContenueAssignment_3_1() { return cContenueAssignment_3_1; }
		
		//EString
		public RuleCall getContenueEStringParserRuleCall_3_1_0() { return cContenueEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class UEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.UE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUEAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPseudoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPseudoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPseudoEStringParserRuleCall_4_1_0 = (RuleCall)cPseudoAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResponsablesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cResponsablesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cResponsablesIntervenantCrossReference_5_2_0 = (CrossReference)cResponsablesAssignment_5_2.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_5_2_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cResponsablesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cResponsablesIntervenantCrossReference_5_3_1_0 = (CrossReference)cResponsablesAssignment_5_3_1.eContents().get(0);
		private final RuleCall cResponsablesIntervenantEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cResponsablesIntervenantCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEnseignantsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cEnseignantsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cEnseignantsIntervenantCrossReference_6_2_0 = (CrossReference)cEnseignantsAssignment_6_2.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_6_2_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cEnseignantsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cEnseignantsIntervenantCrossReference_6_3_1_0 = (CrossReference)cEnseignantsAssignment_6_3_1.eContents().get(0);
		private final RuleCall cEnseignantsIntervenantEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cEnseignantsIntervenantCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDocumentsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cDocumentsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cDocumentsDocumentParserRuleCall_7_2_0 = (RuleCall)cDocumentsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cDocumentsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cDocumentsDocumentParserRuleCall_7_3_1_0 = (RuleCall)cDocumentsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPresentationKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPresentationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPresentationPresentationParserRuleCall_8_1_0 = (RuleCall)cPresentationAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//UE returns UE:
		//    {UE}
		//    'UE'
		//    name=EString
		//    '{'
		//        ('pseudo' pseudo=EString)?
		//        ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//        ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//        ('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
		//        ('presentation' presentation=Presentation)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{UE}
		//'UE'
		//name=EString
		//'{'
		//    ('pseudo' pseudo=EString)?
		//    ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		//    ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		//    ('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
		//    ('presentation' presentation=Presentation)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{UE}
		public Action getUEAction_0() { return cUEAction_0; }
		
		//'UE'
		public Keyword getUEKeyword_1() { return cUEKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('pseudo' pseudo=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'pseudo'
		public Keyword getPseudoKeyword_4_0() { return cPseudoKeyword_4_0; }
		
		//pseudo=EString
		public Assignment getPseudoAssignment_4_1() { return cPseudoAssignment_4_1; }
		
		//EString
		public RuleCall getPseudoEStringParserRuleCall_4_1_0() { return cPseudoEStringParserRuleCall_4_1_0; }
		
		//('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'responsables'
		public Keyword getResponsablesKeyword_5_0() { return cResponsablesKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_5_2() { return cResponsablesAssignment_5_2; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_5_2_0() { return cResponsablesIntervenantCrossReference_5_2_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_5_2_0_1() { return cResponsablesIntervenantEStringParserRuleCall_5_2_0_1; }
		
		//( "," responsables+=[Intervenant|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//responsables+=[Intervenant|EString]
		public Assignment getResponsablesAssignment_5_3_1() { return cResponsablesAssignment_5_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getResponsablesIntervenantCrossReference_5_3_1_0() { return cResponsablesIntervenantCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getResponsablesIntervenantEStringParserRuleCall_5_3_1_0_1() { return cResponsablesIntervenantEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'enseignants'
		public Keyword getEnseignantsKeyword_6_0() { return cEnseignantsKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_6_2() { return cEnseignantsAssignment_6_2; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_6_2_0() { return cEnseignantsIntervenantCrossReference_6_2_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_6_2_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_6_2_0_1; }
		
		//( "," enseignants+=[Intervenant|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//enseignants+=[Intervenant|EString]
		public Assignment getEnseignantsAssignment_6_3_1() { return cEnseignantsAssignment_6_3_1; }
		
		//[Intervenant|EString]
		public CrossReference getEnseignantsIntervenantCrossReference_6_3_1_0() { return cEnseignantsIntervenantCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getEnseignantsIntervenantEStringParserRuleCall_6_3_1_0_1() { return cEnseignantsIntervenantEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'documents'
		public Keyword getDocumentsKeyword_7_0() { return cDocumentsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//documents+=Document
		public Assignment getDocumentsAssignment_7_2() { return cDocumentsAssignment_7_2; }
		
		//Document
		public RuleCall getDocumentsDocumentParserRuleCall_7_2_0() { return cDocumentsDocumentParserRuleCall_7_2_0; }
		
		//( "," documents+=Document)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//documents+=Document
		public Assignment getDocumentsAssignment_7_3_1() { return cDocumentsAssignment_7_3_1; }
		
		//Document
		public RuleCall getDocumentsDocumentParserRuleCall_7_3_1_0() { return cDocumentsDocumentParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('presentation' presentation=Presentation)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'presentation'
		public Keyword getPresentationKeyword_8_0() { return cPresentationKeyword_8_0; }
		
		//presentation=Presentation
		public Assignment getPresentationAssignment_8_1() { return cPresentationAssignment_8_1; }
		
		//Presentation
		public RuleCall getPresentationPresentationParserRuleCall_8_1_0() { return cPresentationPresentationParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class S1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.S1");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cS1Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cS1Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUesoptionnellesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cUesoptionnellesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cUesoptionnellesUECrossReference_3_2_0 = (CrossReference)cUesoptionnellesAssignment_3_2.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_2_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cUesoptionnellesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cUesoptionnellesUECrossReference_3_3_1_0 = (CrossReference)cUesoptionnellesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUesobligatoiresKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cUesobligatoiresAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cUesobligatoiresUECrossReference_4_2_0 = (CrossReference)cUesobligatoiresAssignment_4_2.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_4_2_0_1 = (RuleCall)cUesobligatoiresUECrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cUesobligatoiresAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cUesobligatoiresUECrossReference_4_3_1_0 = (CrossReference)cUesobligatoiresAssignment_4_3_1.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cUesobligatoiresUECrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//S1 returns S1:
		//    {S1}
		//    'S1'
		//    '{'
		//        ('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//        ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{S1}
		//'S1'
		//'{'
		//    ('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//    ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{S1}
		public Action getS1Action_0() { return cS1Action_0; }
		
		//'S1'
		public Keyword getS1Keyword_1() { return cS1Keyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'uesoptionnelles'
		public Keyword getUesoptionnellesKeyword_3_0() { return cUesoptionnellesKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_2() { return cUesoptionnellesAssignment_3_2; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_2_0() { return cUesoptionnellesUECrossReference_3_2_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_2_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_2_0_1; }
		
		//( "," uesoptionnelles+=[UE|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_3_1() { return cUesoptionnellesAssignment_3_3_1; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_3_1_0() { return cUesoptionnellesUECrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_3_1_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'uesobligatoires'
		public Keyword getUesobligatoiresKeyword_4_0() { return cUesobligatoiresKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_4_2() { return cUesobligatoiresAssignment_4_2; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_4_2_0() { return cUesobligatoiresUECrossReference_4_2_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_4_2_0_1() { return cUesobligatoiresUEEStringParserRuleCall_4_2_0_1; }
		
		//( "," uesobligatoires+=[UE|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_4_3_1() { return cUesobligatoiresAssignment_4_3_1; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_4_3_1_0() { return cUesobligatoiresUECrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_4_3_1_0_1() { return cUesobligatoiresUEEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class S2Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.S2");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cS2Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cS2Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUesoptionnellesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cUesoptionnellesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cUesoptionnellesUECrossReference_3_2_0 = (CrossReference)cUesoptionnellesAssignment_3_2.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_2_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cUesoptionnellesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cUesoptionnellesUECrossReference_3_3_1_0 = (CrossReference)cUesoptionnellesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cUesoptionnellesUEEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cUesoptionnellesUECrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUesobligatoiresKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cUesobligatoiresAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cUesobligatoiresUECrossReference_4_2_0 = (CrossReference)cUesobligatoiresAssignment_4_2.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_4_2_0_1 = (RuleCall)cUesobligatoiresUECrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cUesobligatoiresAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cUesobligatoiresUECrossReference_4_3_1_0 = (CrossReference)cUesobligatoiresAssignment_4_3_1.eContents().get(0);
		private final RuleCall cUesobligatoiresUEEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cUesobligatoiresUECrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//S2 returns S2:
		//    {S2}
		//    'S2'
		//    '{'
		//        ('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//        ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{S2}
		//'S2'
		//'{'
		//    ('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		//    ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{S2}
		public Action getS2Action_0() { return cS2Action_0; }
		
		//'S2'
		public Keyword getS2Keyword_1() { return cS2Keyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'uesoptionnelles'
		public Keyword getUesoptionnellesKeyword_3_0() { return cUesoptionnellesKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_2() { return cUesoptionnellesAssignment_3_2; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_2_0() { return cUesoptionnellesUECrossReference_3_2_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_2_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_2_0_1; }
		
		//( "," uesoptionnelles+=[UE|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//uesoptionnelles+=[UE|EString]
		public Assignment getUesoptionnellesAssignment_3_3_1() { return cUesoptionnellesAssignment_3_3_1; }
		
		//[UE|EString]
		public CrossReference getUesoptionnellesUECrossReference_3_3_1_0() { return cUesoptionnellesUECrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getUesoptionnellesUEEStringParserRuleCall_3_3_1_0_1() { return cUesoptionnellesUEEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'uesobligatoires'
		public Keyword getUesobligatoiresKeyword_4_0() { return cUesobligatoiresKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_4_2() { return cUesobligatoiresAssignment_4_2; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_4_2_0() { return cUesobligatoiresUECrossReference_4_2_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_4_2_0_1() { return cUesobligatoiresUEEStringParserRuleCall_4_2_0_1; }
		
		//( "," uesobligatoires+=[UE|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//uesobligatoires+=[UE|EString]
		public Assignment getUesobligatoiresAssignment_4_3_1() { return cUesobligatoiresAssignment_4_3_1; }
		
		//[UE|EString]
		public CrossReference getUesobligatoiresUECrossReference_4_3_1_0() { return cUesobligatoiresUECrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getUesobligatoiresUEEStringParserRuleCall_4_3_1_0_1() { return cUesobligatoiresUEEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class VideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Video");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVideoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVideoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLienKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLienAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLienEStringParserRuleCall_5_1_0 = (RuleCall)cLienAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDureeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDureeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDureeEStringParserRuleCall_6_1_0 = (RuleCall)cDureeAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Video returns Video:
		//    {Video}
		//    'Video'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('lien' lien=EString)?
		//        ('duree' duree=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Video}
		//'Video'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('lien' lien=EString)?
		//    ('duree' duree=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Video}
		public Action getVideoAction_0() { return cVideoAction_0; }
		
		//'Video'
		public Keyword getVideoKeyword_1() { return cVideoKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('lien' lien=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lien'
		public Keyword getLienKeyword_5_0() { return cLienKeyword_5_0; }
		
		//lien=EString
		public Assignment getLienAssignment_5_1() { return cLienAssignment_5_1; }
		
		//EString
		public RuleCall getLienEStringParserRuleCall_5_1_0() { return cLienEStringParserRuleCall_5_1_0; }
		
		//('duree' duree=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'duree'
		public Keyword getDureeKeyword_6_0() { return cDureeKeyword_6_0; }
		
		//duree=EString
		public Assignment getDureeAssignment_6_1() { return cDureeAssignment_6_1; }
		
		//EString
		public RuleCall getDureeEStringParserRuleCall_6_1_0() { return cDureeEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class FichierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Fichier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFichierAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFichierKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLienKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLienAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLienEStringParserRuleCall_5_1_0 = (RuleCall)cLienAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAuteurKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cAuteurAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cAuteurEStringParserRuleCall_6_1_0 = (RuleCall)cAuteurAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Fichier returns Fichier:
		//    {Fichier}
		//    'Fichier'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('lien' lien=EString)?
		//        ('auteur' auteur=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Fichier}
		//'Fichier'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('lien' lien=EString)?
		//    ('auteur' auteur=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Fichier}
		public Action getFichierAction_0() { return cFichierAction_0; }
		
		//'Fichier'
		public Keyword getFichierKeyword_1() { return cFichierKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('lien' lien=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lien'
		public Keyword getLienKeyword_5_0() { return cLienKeyword_5_0; }
		
		//lien=EString
		public Assignment getLienAssignment_5_1() { return cLienAssignment_5_1; }
		
		//EString
		public RuleCall getLienEStringParserRuleCall_5_1_0() { return cLienEStringParserRuleCall_5_1_0; }
		
		//('auteur' auteur=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'auteur'
		public Keyword getAuteurKeyword_6_0() { return cAuteurKeyword_6_0; }
		
		//auteur=EString
		public Assignment getAuteurAssignment_6_1() { return cAuteurAssignment_6_1; }
		
		//EString
		public RuleCall getAuteurEStringParserRuleCall_6_1_0() { return cAuteurEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AudioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fil.xtext.LangFil.Audio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAudioAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAudioKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLienKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLienAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLienEStringParserRuleCall_5_1_0 = (RuleCall)cLienAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDureeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDureeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDureeEStringParserRuleCall_6_1_0 = (RuleCall)cDureeAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Audio returns Audio:
		//    {Audio}
		//    'Audio'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('lien' lien=EString)?
		//        ('duree' duree=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Audio}
		//'Audio'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('lien' lien=EString)?
		//    ('duree' duree=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Audio}
		public Action getAudioAction_0() { return cAudioAction_0; }
		
		//'Audio'
		public Keyword getAudioKeyword_1() { return cAudioKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('lien' lien=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lien'
		public Keyword getLienKeyword_5_0() { return cLienKeyword_5_0; }
		
		//lien=EString
		public Assignment getLienAssignment_5_1() { return cLienAssignment_5_1; }
		
		//EString
		public RuleCall getLienEStringParserRuleCall_5_1_0() { return cLienEStringParserRuleCall_5_1_0; }
		
		//('duree' duree=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'duree'
		public Keyword getDureeKeyword_6_0() { return cDureeKeyword_6_0; }
		
		//duree=EString
		public Assignment getDureeAssignment_6_1() { return cDureeAssignment_6_1; }
		
		//EString
		public RuleCall getDureeEStringParserRuleCall_6_1_0() { return cDureeEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final FaculteElements pFaculte;
	private final DocumentElements pDocument;
	private final EStringElements pEString;
	private final NiveauElements pNiveau;
	private final IntervenantElements pIntervenant;
	private final FormationElements pFormation;
	private final PresentationElements pPresentation;
	private final UEElements pUE;
	private final S1Elements pS1;
	private final S2Elements pS2;
	private final VideoElements pVideo;
	private final FichierElements pFichier;
	private final AudioElements pAudio;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LangFilGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFaculte = new FaculteElements();
		this.pDocument = new DocumentElements();
		this.pEString = new EStringElements();
		this.pNiveau = new NiveauElements();
		this.pIntervenant = new IntervenantElements();
		this.pFormation = new FormationElements();
		this.pPresentation = new PresentationElements();
		this.pUE = new UEElements();
		this.pS1 = new S1Elements();
		this.pS2 = new S2Elements();
		this.pVideo = new VideoElements();
		this.pFichier = new FichierElements();
		this.pAudio = new AudioElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fil.xtext.LangFil".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Faculte returns Faculte:
	//    {Faculte}
	//    'Faculte'
	//    name=EString
	//    '{'
	//        ('niveaux' '{' niveaux+=Niveau ( "," niveaux+=Niveau)* '}' )?
	//        ('intervenants' '{' intervenants+=Intervenant ( "," intervenants+=Intervenant)* '}' )?
	//    '}';
	public FaculteElements getFaculteAccess() {
		return pFaculte;
	}
	
	public ParserRule getFaculteRule() {
		return getFaculteAccess().getRule();
	}
	
	//Document returns Document:
	//    Video | Fichier | Audio;
	public DocumentElements getDocumentAccess() {
		return pDocument;
	}
	
	public ParserRule getDocumentRule() {
		return getDocumentAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Niveau returns Niveau:
	//    {Niveau}
	//    'Niveau'
	//    name=EString
	//    '{'
	//        ('pseudo' pseudo=EString)?
	//        ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
	//        ('formations' '{' formations+=Formation ( "," formations+=Formation)* '}' )?
	//        ('presentation' presentation=Presentation)?
	//        ('ues' '{' ues+=UE ( "," ues+=UE)* '}' )?
	//    '}';
	public NiveauElements getNiveauAccess() {
		return pNiveau;
	}
	
	public ParserRule getNiveauRule() {
		return getNiveauAccess().getRule();
	}
	
	//Intervenant returns Intervenant:
	//    {Intervenant}
	//    'Intervenant'
	//    name=EString
	//    '{'
	//        ('prenom' prenom=EString)?
	//    '}';
	public IntervenantElements getIntervenantAccess() {
		return pIntervenant;
	}
	
	public ParserRule getIntervenantRule() {
		return getIntervenantAccess().getRule();
	}
	
	//Formation returns Formation:
	//    'Formation'
	//    name=EString
	//    '{'
	//        ('pseudo' pseudo=EString)?
	//        ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
	//        ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
	//        ('presentation' presentation=Presentation)?
	//        's1' s1=S1
	//        's2' s2=S2
	//        ('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
	//    '}';
	public FormationElements getFormationAccess() {
		return pFormation;
	}
	
	public ParserRule getFormationRule() {
		return getFormationAccess().getRule();
	}
	
	//Presentation returns Presentation:
	//    {Presentation}
	//    'Presentation'
	//    '{'
	//        ('contenue' contenue=EString)?
	//    '}';
	public PresentationElements getPresentationAccess() {
		return pPresentation;
	}
	
	public ParserRule getPresentationRule() {
		return getPresentationAccess().getRule();
	}
	
	//UE returns UE:
	//    {UE}
	//    'UE'
	//    name=EString
	//    '{'
	//        ('pseudo' pseudo=EString)?
	//        ('responsables' '(' responsables+=[Intervenant|EString] ( "," responsables+=[Intervenant|EString])* ')' )?
	//        ('enseignants' '(' enseignants+=[Intervenant|EString] ( "," enseignants+=[Intervenant|EString])* ')' )?
	//        ('documents' '{' documents+=Document ( "," documents+=Document)* '}' )?
	//        ('presentation' presentation=Presentation)?
	//    '}';
	public UEElements getUEAccess() {
		return pUE;
	}
	
	public ParserRule getUERule() {
		return getUEAccess().getRule();
	}
	
	//S1 returns S1:
	//    {S1}
	//    'S1'
	//    '{'
	//        ('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
	//        ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
	//    '}';
	public S1Elements getS1Access() {
		return pS1;
	}
	
	public ParserRule getS1Rule() {
		return getS1Access().getRule();
	}
	
	//S2 returns S2:
	//    {S2}
	//    'S2'
	//    '{'
	//        ('uesoptionnelles' '(' uesoptionnelles+=[UE|EString] ( "," uesoptionnelles+=[UE|EString])* ')' )?
	//        ('uesobligatoires' '(' uesobligatoires+=[UE|EString] ( "," uesobligatoires+=[UE|EString])* ')' )?
	//    '}';
	public S2Elements getS2Access() {
		return pS2;
	}
	
	public ParserRule getS2Rule() {
		return getS2Access().getRule();
	}
	
	//Video returns Video:
	//    {Video}
	//    'Video'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('lien' lien=EString)?
	//        ('duree' duree=EString)?
	//    '}';
	public VideoElements getVideoAccess() {
		return pVideo;
	}
	
	public ParserRule getVideoRule() {
		return getVideoAccess().getRule();
	}
	
	//Fichier returns Fichier:
	//    {Fichier}
	//    'Fichier'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('lien' lien=EString)?
	//        ('auteur' auteur=EString)?
	//    '}';
	public FichierElements getFichierAccess() {
		return pFichier;
	}
	
	public ParserRule getFichierRule() {
		return getFichierAccess().getRule();
	}
	
	//Audio returns Audio:
	//    {Audio}
	//    'Audio'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('lien' lien=EString)?
	//        ('duree' duree=EString)?
	//    '}';
	public AudioElements getAudioAccess() {
		return pAudio;
	}
	
	public ParserRule getAudioRule() {
		return getAudioAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
