/*
 * generated by Xtext 2.25.0
 */
package fil.xtextfil.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fil.xtextfil.ide.contentassist.antlr.internal.InternalLangFilParser;
import fil.xtextfil.services.LangFilGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LangFilParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LangFilGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LangFilGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getFaculteAccess().getGroup(), "rule__Faculte__Group__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_4(), "rule__Faculte__Group_4__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_4_3(), "rule__Faculte__Group_4_3__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_5(), "rule__Faculte__Group_5__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_5_3(), "rule__Faculte__Group_5_3__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup(), "rule__Niveau__Group__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_3(), "rule__Niveau__Group_3__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_4(), "rule__Niveau__Group_4__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup(), "rule__Intervenant__Group__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_5(), "rule__Intervenant__Group_5__0");
			builder.put(grammarAccess.getFaculteAccess().getNomAssignment_3(), "rule__Faculte__NomAssignment_3");
			builder.put(grammarAccess.getFaculteAccess().getNiveauxAssignment_4_2(), "rule__Faculte__NiveauxAssignment_4_2");
			builder.put(grammarAccess.getFaculteAccess().getNiveauxAssignment_4_3_1(), "rule__Faculte__NiveauxAssignment_4_3_1");
			builder.put(grammarAccess.getFaculteAccess().getIntervenantsAssignment_5_2(), "rule__Faculte__IntervenantsAssignment_5_2");
			builder.put(grammarAccess.getFaculteAccess().getIntervenantsAssignment_5_3_1(), "rule__Faculte__IntervenantsAssignment_5_3_1");
			builder.put(grammarAccess.getNiveauAccess().getNomAssignment_3_1(), "rule__Niveau__NomAssignment_3_1");
			builder.put(grammarAccess.getNiveauAccess().getPseudoAssignment_4_1(), "rule__Niveau__PseudoAssignment_4_1");
			builder.put(grammarAccess.getIntervenantAccess().getNomAssignment_4(), "rule__Intervenant__NomAssignment_4");
			builder.put(grammarAccess.getIntervenantAccess().getPrenomAssignment_5_1(), "rule__Intervenant__PrenomAssignment_5_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LangFilGrammarAccess grammarAccess;

	@Override
	protected InternalLangFilParser createParser() {
		InternalLangFilParser result = new InternalLangFilParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LangFilGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LangFilGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
