/*
 * generated by Xtext 2.25.0
 */
package fil.xtextfil;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LangFilStandaloneSetup extends LangFilStandaloneSetupGenerated {

	public static void doSetup() {
		new LangFilStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
