/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.parser.antlr;

import com.google.inject.Inject;
import fil.xtext.parser.antlr.internal.InternalLangFilParser;
import fil.xtext.services.LangFilGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LangFilParser extends AbstractAntlrParser {

	@Inject
	private LangFilGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLangFilParser createParser(XtextTokenStream stream) {
		return new InternalLangFilParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Faculte";
	}

	public LangFilGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LangFilGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
