/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fil.xtext.ide.contentassist.antlr.internal.InternalLangFilParser;
import fil.xtext.services.LangFilGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LangFilParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LangFilGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LangFilGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDocumentAccess().getAlternatives(), "rule__Document__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getFaculteAccess().getGroup(), "rule__Faculte__Group__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_4(), "rule__Faculte__Group_4__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_4_3(), "rule__Faculte__Group_4_3__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_5(), "rule__Faculte__Group_5__0");
			builder.put(grammarAccess.getFaculteAccess().getGroup_5_3(), "rule__Faculte__Group_5_3__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup(), "rule__Niveau__Group__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_4(), "rule__Niveau__Group_4__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_5(), "rule__Niveau__Group_5__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_5_3(), "rule__Niveau__Group_5_3__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_6(), "rule__Niveau__Group_6__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_6_3(), "rule__Niveau__Group_6_3__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_7(), "rule__Niveau__Group_7__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_8(), "rule__Niveau__Group_8__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_8_3(), "rule__Niveau__Group_8_3__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup(), "rule__Intervenant__Group__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_4(), "rule__Intervenant__Group_4__0");
			builder.put(grammarAccess.getFormationAccess().getGroup(), "rule__Formation__Group__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_3(), "rule__Formation__Group_3__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4(), "rule__Formation__Group_4__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4_3(), "rule__Formation__Group_4_3__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_5(), "rule__Formation__Group_5__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_5_3(), "rule__Formation__Group_5_3__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_6(), "rule__Formation__Group_6__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_11(), "rule__Formation__Group_11__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_11_3(), "rule__Formation__Group_11_3__0");
			builder.put(grammarAccess.getPresentationAccess().getGroup(), "rule__Presentation__Group__0");
			builder.put(grammarAccess.getPresentationAccess().getGroup_3(), "rule__Presentation__Group_3__0");
			builder.put(grammarAccess.getUEAccess().getGroup(), "rule__UE__Group__0");
			builder.put(grammarAccess.getUEAccess().getGroup_4(), "rule__UE__Group_4__0");
			builder.put(grammarAccess.getUEAccess().getGroup_5(), "rule__UE__Group_5__0");
			builder.put(grammarAccess.getUEAccess().getGroup_5_3(), "rule__UE__Group_5_3__0");
			builder.put(grammarAccess.getUEAccess().getGroup_6(), "rule__UE__Group_6__0");
			builder.put(grammarAccess.getUEAccess().getGroup_6_3(), "rule__UE__Group_6_3__0");
			builder.put(grammarAccess.getUEAccess().getGroup_7(), "rule__UE__Group_7__0");
			builder.put(grammarAccess.getUEAccess().getGroup_7_3(), "rule__UE__Group_7_3__0");
			builder.put(grammarAccess.getUEAccess().getGroup_8(), "rule__UE__Group_8__0");
			builder.put(grammarAccess.getS1Access().getGroup(), "rule__S1__Group__0");
			builder.put(grammarAccess.getS1Access().getGroup_3(), "rule__S1__Group_3__0");
			builder.put(grammarAccess.getS1Access().getGroup_3_3(), "rule__S1__Group_3_3__0");
			builder.put(grammarAccess.getS1Access().getGroup_4(), "rule__S1__Group_4__0");
			builder.put(grammarAccess.getS1Access().getGroup_4_3(), "rule__S1__Group_4_3__0");
			builder.put(grammarAccess.getS2Access().getGroup(), "rule__S2__Group__0");
			builder.put(grammarAccess.getS2Access().getGroup_3(), "rule__S2__Group_3__0");
			builder.put(grammarAccess.getS2Access().getGroup_3_3(), "rule__S2__Group_3_3__0");
			builder.put(grammarAccess.getS2Access().getGroup_4(), "rule__S2__Group_4__0");
			builder.put(grammarAccess.getS2Access().getGroup_4_3(), "rule__S2__Group_4_3__0");
			builder.put(grammarAccess.getVideoAccess().getGroup(), "rule__Video__Group__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_4(), "rule__Video__Group_4__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_5(), "rule__Video__Group_5__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_6(), "rule__Video__Group_6__0");
			builder.put(grammarAccess.getFichierAccess().getGroup(), "rule__Fichier__Group__0");
			builder.put(grammarAccess.getFichierAccess().getGroup_4(), "rule__Fichier__Group_4__0");
			builder.put(grammarAccess.getFichierAccess().getGroup_5(), "rule__Fichier__Group_5__0");
			builder.put(grammarAccess.getFichierAccess().getGroup_6(), "rule__Fichier__Group_6__0");
			builder.put(grammarAccess.getAudioAccess().getGroup(), "rule__Audio__Group__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_4(), "rule__Audio__Group_4__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_5(), "rule__Audio__Group_5__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_6(), "rule__Audio__Group_6__0");
			builder.put(grammarAccess.getFaculteAccess().getNameAssignment_2(), "rule__Faculte__NameAssignment_2");
			builder.put(grammarAccess.getFaculteAccess().getNiveauxAssignment_4_2(), "rule__Faculte__NiveauxAssignment_4_2");
			builder.put(grammarAccess.getFaculteAccess().getNiveauxAssignment_4_3_1(), "rule__Faculte__NiveauxAssignment_4_3_1");
			builder.put(grammarAccess.getFaculteAccess().getIntervenantsAssignment_5_2(), "rule__Faculte__IntervenantsAssignment_5_2");
			builder.put(grammarAccess.getFaculteAccess().getIntervenantsAssignment_5_3_1(), "rule__Faculte__IntervenantsAssignment_5_3_1");
			builder.put(grammarAccess.getNiveauAccess().getNameAssignment_2(), "rule__Niveau__NameAssignment_2");
			builder.put(grammarAccess.getNiveauAccess().getPseudoAssignment_4_1(), "rule__Niveau__PseudoAssignment_4_1");
			builder.put(grammarAccess.getNiveauAccess().getResponsablesAssignment_5_2(), "rule__Niveau__ResponsablesAssignment_5_2");
			builder.put(grammarAccess.getNiveauAccess().getResponsablesAssignment_5_3_1(), "rule__Niveau__ResponsablesAssignment_5_3_1");
			builder.put(grammarAccess.getNiveauAccess().getFormationsAssignment_6_2(), "rule__Niveau__FormationsAssignment_6_2");
			builder.put(grammarAccess.getNiveauAccess().getFormationsAssignment_6_3_1(), "rule__Niveau__FormationsAssignment_6_3_1");
			builder.put(grammarAccess.getNiveauAccess().getPresentationAssignment_7_1(), "rule__Niveau__PresentationAssignment_7_1");
			builder.put(grammarAccess.getNiveauAccess().getUesAssignment_8_2(), "rule__Niveau__UesAssignment_8_2");
			builder.put(grammarAccess.getNiveauAccess().getUesAssignment_8_3_1(), "rule__Niveau__UesAssignment_8_3_1");
			builder.put(grammarAccess.getIntervenantAccess().getNameAssignment_2(), "rule__Intervenant__NameAssignment_2");
			builder.put(grammarAccess.getIntervenantAccess().getPrenomAssignment_4_1(), "rule__Intervenant__PrenomAssignment_4_1");
			builder.put(grammarAccess.getFormationAccess().getNameAssignment_1(), "rule__Formation__NameAssignment_1");
			builder.put(grammarAccess.getFormationAccess().getPseudoAssignment_3_1(), "rule__Formation__PseudoAssignment_3_1");
			builder.put(grammarAccess.getFormationAccess().getResponsablesAssignment_4_2(), "rule__Formation__ResponsablesAssignment_4_2");
			builder.put(grammarAccess.getFormationAccess().getResponsablesAssignment_4_3_1(), "rule__Formation__ResponsablesAssignment_4_3_1");
			builder.put(grammarAccess.getFormationAccess().getEnseignantsAssignment_5_2(), "rule__Formation__EnseignantsAssignment_5_2");
			builder.put(grammarAccess.getFormationAccess().getEnseignantsAssignment_5_3_1(), "rule__Formation__EnseignantsAssignment_5_3_1");
			builder.put(grammarAccess.getFormationAccess().getPresentationAssignment_6_1(), "rule__Formation__PresentationAssignment_6_1");
			builder.put(grammarAccess.getFormationAccess().getS1Assignment_8(), "rule__Formation__S1Assignment_8");
			builder.put(grammarAccess.getFormationAccess().getS2Assignment_10(), "rule__Formation__S2Assignment_10");
			builder.put(grammarAccess.getFormationAccess().getDocumentsAssignment_11_2(), "rule__Formation__DocumentsAssignment_11_2");
			builder.put(grammarAccess.getFormationAccess().getDocumentsAssignment_11_3_1(), "rule__Formation__DocumentsAssignment_11_3_1");
			builder.put(grammarAccess.getPresentationAccess().getContenueAssignment_3_1(), "rule__Presentation__ContenueAssignment_3_1");
			builder.put(grammarAccess.getUEAccess().getNameAssignment_2(), "rule__UE__NameAssignment_2");
			builder.put(grammarAccess.getUEAccess().getPseudoAssignment_4_1(), "rule__UE__PseudoAssignment_4_1");
			builder.put(grammarAccess.getUEAccess().getResponsablesAssignment_5_2(), "rule__UE__ResponsablesAssignment_5_2");
			builder.put(grammarAccess.getUEAccess().getResponsablesAssignment_5_3_1(), "rule__UE__ResponsablesAssignment_5_3_1");
			builder.put(grammarAccess.getUEAccess().getEnseignantsAssignment_6_2(), "rule__UE__EnseignantsAssignment_6_2");
			builder.put(grammarAccess.getUEAccess().getEnseignantsAssignment_6_3_1(), "rule__UE__EnseignantsAssignment_6_3_1");
			builder.put(grammarAccess.getUEAccess().getDocumentsAssignment_7_2(), "rule__UE__DocumentsAssignment_7_2");
			builder.put(grammarAccess.getUEAccess().getDocumentsAssignment_7_3_1(), "rule__UE__DocumentsAssignment_7_3_1");
			builder.put(grammarAccess.getUEAccess().getPresentationAssignment_8_1(), "rule__UE__PresentationAssignment_8_1");
			builder.put(grammarAccess.getS1Access().getUesoptionnellesAssignment_3_2(), "rule__S1__UesoptionnellesAssignment_3_2");
			builder.put(grammarAccess.getS1Access().getUesoptionnellesAssignment_3_3_1(), "rule__S1__UesoptionnellesAssignment_3_3_1");
			builder.put(grammarAccess.getS1Access().getUesobligatoiresAssignment_4_2(), "rule__S1__UesobligatoiresAssignment_4_2");
			builder.put(grammarAccess.getS1Access().getUesobligatoiresAssignment_4_3_1(), "rule__S1__UesobligatoiresAssignment_4_3_1");
			builder.put(grammarAccess.getS2Access().getUesoptionnellesAssignment_3_2(), "rule__S2__UesoptionnellesAssignment_3_2");
			builder.put(grammarAccess.getS2Access().getUesoptionnellesAssignment_3_3_1(), "rule__S2__UesoptionnellesAssignment_3_3_1");
			builder.put(grammarAccess.getS2Access().getUesobligatoiresAssignment_4_2(), "rule__S2__UesobligatoiresAssignment_4_2");
			builder.put(grammarAccess.getS2Access().getUesobligatoiresAssignment_4_3_1(), "rule__S2__UesobligatoiresAssignment_4_3_1");
			builder.put(grammarAccess.getVideoAccess().getNameAssignment_2(), "rule__Video__NameAssignment_2");
			builder.put(grammarAccess.getVideoAccess().getDescriptionAssignment_4_1(), "rule__Video__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getVideoAccess().getLienAssignment_5_1(), "rule__Video__LienAssignment_5_1");
			builder.put(grammarAccess.getVideoAccess().getDureeAssignment_6_1(), "rule__Video__DureeAssignment_6_1");
			builder.put(grammarAccess.getFichierAccess().getNameAssignment_2(), "rule__Fichier__NameAssignment_2");
			builder.put(grammarAccess.getFichierAccess().getDescriptionAssignment_4_1(), "rule__Fichier__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getFichierAccess().getLienAssignment_5_1(), "rule__Fichier__LienAssignment_5_1");
			builder.put(grammarAccess.getFichierAccess().getAuteurAssignment_6_1(), "rule__Fichier__AuteurAssignment_6_1");
			builder.put(grammarAccess.getAudioAccess().getNameAssignment_2(), "rule__Audio__NameAssignment_2");
			builder.put(grammarAccess.getAudioAccess().getDescriptionAssignment_4_1(), "rule__Audio__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAudioAccess().getLienAssignment_5_1(), "rule__Audio__LienAssignment_5_1");
			builder.put(grammarAccess.getAudioAccess().getDureeAssignment_6_1(), "rule__Audio__DureeAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LangFilGrammarAccess grammarAccess;

	@Override
	protected InternalLangFilParser createParser() {
		InternalLangFilParser result = new InternalLangFilParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LangFilGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LangFilGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
