/*
 * generated by Xtext 2.25.0
 */
package fil.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fil.xtext.ide.contentassist.antlr.internal.InternalLangFilParser;
import fil.xtext.services.LangFilGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LangFilParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LangFilGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LangFilGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFaculteAccess().getAlternatives_3(), "rule__Faculte__Alternatives_3");
			builder.put(grammarAccess.getDocumentAccess().getAlternatives(), "rule__Document__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getNiveauAccess().getAlternatives_4_3(), "rule__Niveau__Alternatives_4_3");
			builder.put(grammarAccess.getFaculteAccess().getGroup(), "rule__Faculte__Group__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup(), "rule__Niveau__Group__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_4_0(), "rule__Niveau__Group_4_0__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_4_1(), "rule__Niveau__Group_4_1__0");
			builder.put(grammarAccess.getNiveauAccess().getGroup_4_1_3(), "rule__Niveau__Group_4_1_3__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup(), "rule__Intervenant__Group__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_4(), "rule__Intervenant__Group_4__0");
			builder.put(grammarAccess.getFormationAccess().getGroup(), "rule__Formation__Group__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4_0(), "rule__Formation__Group_4_0__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4_1(), "rule__Formation__Group_4_1__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4_1_3(), "rule__Formation__Group_4_1_3__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4_2(), "rule__Formation__Group_4_2__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_4_2_3(), "rule__Formation__Group_4_2_3__0");
			builder.put(grammarAccess.getPresentationAccess().getGroup(), "rule__Presentation__Group__0");
			builder.put(grammarAccess.getUEAccess().getGroup(), "rule__UE__Group__0");
			builder.put(grammarAccess.getUEAccess().getGroup_4_0(), "rule__UE__Group_4_0__0");
			builder.put(grammarAccess.getUEAccess().getGroup_4_2(), "rule__UE__Group_4_2__0");
			builder.put(grammarAccess.getUEAccess().getGroup_4_2_3(), "rule__UE__Group_4_2_3__0");
			builder.put(grammarAccess.getUEAccess().getGroup_4_3(), "rule__UE__Group_4_3__0");
			builder.put(grammarAccess.getUEAccess().getGroup_4_3_3(), "rule__UE__Group_4_3_3__0");
			builder.put(grammarAccess.getS1Access().getGroup(), "rule__S1__Group__0");
			builder.put(grammarAccess.getS1Access().getGroup_3_0(), "rule__S1__Group_3_0__0");
			builder.put(grammarAccess.getS1Access().getGroup_3_0_3(), "rule__S1__Group_3_0_3__0");
			builder.put(grammarAccess.getS1Access().getGroup_3_1(), "rule__S1__Group_3_1__0");
			builder.put(grammarAccess.getS1Access().getGroup_3_1_3(), "rule__S1__Group_3_1_3__0");
			builder.put(grammarAccess.getS2Access().getGroup(), "rule__S2__Group__0");
			builder.put(grammarAccess.getS2Access().getGroup_3_0(), "rule__S2__Group_3_0__0");
			builder.put(grammarAccess.getS2Access().getGroup_3_0_3(), "rule__S2__Group_3_0_3__0");
			builder.put(grammarAccess.getS2Access().getGroup_3_1(), "rule__S2__Group_3_1__0");
			builder.put(grammarAccess.getS2Access().getGroup_3_1_3(), "rule__S2__Group_3_1_3__0");
			builder.put(grammarAccess.getVideoAccess().getGroup(), "rule__Video__Group__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_4(), "rule__Video__Group_4__0");
			builder.put(grammarAccess.getVideoAccess().getGroup_7(), "rule__Video__Group_7__0");
			builder.put(grammarAccess.getFichierAccess().getGroup(), "rule__Fichier__Group__0");
			builder.put(grammarAccess.getFichierAccess().getGroup_4(), "rule__Fichier__Group_4__0");
			builder.put(grammarAccess.getFichierAccess().getGroup_7(), "rule__Fichier__Group_7__0");
			builder.put(grammarAccess.getAudioAccess().getGroup(), "rule__Audio__Group__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_4(), "rule__Audio__Group_4__0");
			builder.put(grammarAccess.getAudioAccess().getGroup_7(), "rule__Audio__Group_7__0");
			builder.put(grammarAccess.getFaculteAccess().getNameAssignment_2(), "rule__Faculte__NameAssignment_2");
			builder.put(grammarAccess.getFaculteAccess().getNiveauxAssignment_3_0(), "rule__Faculte__NiveauxAssignment_3_0");
			builder.put(grammarAccess.getFaculteAccess().getIntervenantsAssignment_3_1(), "rule__Faculte__IntervenantsAssignment_3_1");
			builder.put(grammarAccess.getNiveauAccess().getNameAssignment_2(), "rule__Niveau__NameAssignment_2");
			builder.put(grammarAccess.getNiveauAccess().getPseudoAssignment_4_0_1(), "rule__Niveau__PseudoAssignment_4_0_1");
			builder.put(grammarAccess.getNiveauAccess().getResponsablesAssignment_4_1_2(), "rule__Niveau__ResponsablesAssignment_4_1_2");
			builder.put(grammarAccess.getNiveauAccess().getResponsablesAssignment_4_1_3_1(), "rule__Niveau__ResponsablesAssignment_4_1_3_1");
			builder.put(grammarAccess.getNiveauAccess().getPresentationAssignment_4_2(), "rule__Niveau__PresentationAssignment_4_2");
			builder.put(grammarAccess.getNiveauAccess().getFormationsAssignment_4_3_0(), "rule__Niveau__FormationsAssignment_4_3_0");
			builder.put(grammarAccess.getNiveauAccess().getUesAssignment_4_3_1(), "rule__Niveau__UesAssignment_4_3_1");
			builder.put(grammarAccess.getIntervenantAccess().getNameAssignment_2(), "rule__Intervenant__NameAssignment_2");
			builder.put(grammarAccess.getIntervenantAccess().getPrenomAssignment_4_1(), "rule__Intervenant__PrenomAssignment_4_1");
			builder.put(grammarAccess.getFormationAccess().getNameAssignment_2(), "rule__Formation__NameAssignment_2");
			builder.put(grammarAccess.getFormationAccess().getPseudoAssignment_4_0_1(), "rule__Formation__PseudoAssignment_4_0_1");
			builder.put(grammarAccess.getFormationAccess().getResponsablesAssignment_4_1_2(), "rule__Formation__ResponsablesAssignment_4_1_2");
			builder.put(grammarAccess.getFormationAccess().getResponsablesAssignment_4_1_3_1(), "rule__Formation__ResponsablesAssignment_4_1_3_1");
			builder.put(grammarAccess.getFormationAccess().getEnseignantsAssignment_4_2_2(), "rule__Formation__EnseignantsAssignment_4_2_2");
			builder.put(grammarAccess.getFormationAccess().getEnseignantsAssignment_4_2_3_1(), "rule__Formation__EnseignantsAssignment_4_2_3_1");
			builder.put(grammarAccess.getFormationAccess().getPresentationAssignment_4_3(), "rule__Formation__PresentationAssignment_4_3");
			builder.put(grammarAccess.getFormationAccess().getS1Assignment_4_4(), "rule__Formation__S1Assignment_4_4");
			builder.put(grammarAccess.getFormationAccess().getS2Assignment_4_5(), "rule__Formation__S2Assignment_4_5");
			builder.put(grammarAccess.getFormationAccess().getDocumentsAssignment_4_6(), "rule__Formation__DocumentsAssignment_4_6");
			builder.put(grammarAccess.getPresentationAccess().getContenueAssignment_2(), "rule__Presentation__ContenueAssignment_2");
			builder.put(grammarAccess.getUEAccess().getNameAssignment_2(), "rule__UE__NameAssignment_2");
			builder.put(grammarAccess.getUEAccess().getPseudoAssignment_4_0_1(), "rule__UE__PseudoAssignment_4_0_1");
			builder.put(grammarAccess.getUEAccess().getPresentationAssignment_4_1(), "rule__UE__PresentationAssignment_4_1");
			builder.put(grammarAccess.getUEAccess().getResponsablesAssignment_4_2_2(), "rule__UE__ResponsablesAssignment_4_2_2");
			builder.put(grammarAccess.getUEAccess().getResponsablesAssignment_4_2_3_1(), "rule__UE__ResponsablesAssignment_4_2_3_1");
			builder.put(grammarAccess.getUEAccess().getEnseignantsAssignment_4_3_2(), "rule__UE__EnseignantsAssignment_4_3_2");
			builder.put(grammarAccess.getUEAccess().getEnseignantsAssignment_4_3_3_1(), "rule__UE__EnseignantsAssignment_4_3_3_1");
			builder.put(grammarAccess.getUEAccess().getDocumentsAssignment_4_4(), "rule__UE__DocumentsAssignment_4_4");
			builder.put(grammarAccess.getS1Access().getUesoptionnellesAssignment_3_0_2(), "rule__S1__UesoptionnellesAssignment_3_0_2");
			builder.put(grammarAccess.getS1Access().getUesoptionnellesAssignment_3_0_3_1(), "rule__S1__UesoptionnellesAssignment_3_0_3_1");
			builder.put(grammarAccess.getS1Access().getUesobligatoiresAssignment_3_1_2(), "rule__S1__UesobligatoiresAssignment_3_1_2");
			builder.put(grammarAccess.getS1Access().getUesobligatoiresAssignment_3_1_3_1(), "rule__S1__UesobligatoiresAssignment_3_1_3_1");
			builder.put(grammarAccess.getS2Access().getUesoptionnellesAssignment_3_0_2(), "rule__S2__UesoptionnellesAssignment_3_0_2");
			builder.put(grammarAccess.getS2Access().getUesoptionnellesAssignment_3_0_3_1(), "rule__S2__UesoptionnellesAssignment_3_0_3_1");
			builder.put(grammarAccess.getS2Access().getUesobligatoiresAssignment_3_1_2(), "rule__S2__UesobligatoiresAssignment_3_1_2");
			builder.put(grammarAccess.getS2Access().getUesobligatoiresAssignment_3_1_3_1(), "rule__S2__UesobligatoiresAssignment_3_1_3_1");
			builder.put(grammarAccess.getVideoAccess().getNameAssignment_2(), "rule__Video__NameAssignment_2");
			builder.put(grammarAccess.getVideoAccess().getDescriptionAssignment_4_1(), "rule__Video__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getVideoAccess().getLienAssignment_6(), "rule__Video__LienAssignment_6");
			builder.put(grammarAccess.getVideoAccess().getDureeAssignment_7_1(), "rule__Video__DureeAssignment_7_1");
			builder.put(grammarAccess.getFichierAccess().getNameAssignment_2(), "rule__Fichier__NameAssignment_2");
			builder.put(grammarAccess.getFichierAccess().getDescriptionAssignment_4_1(), "rule__Fichier__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getFichierAccess().getLienAssignment_6(), "rule__Fichier__LienAssignment_6");
			builder.put(grammarAccess.getFichierAccess().getAuteurAssignment_7_1(), "rule__Fichier__AuteurAssignment_7_1");
			builder.put(grammarAccess.getAudioAccess().getNameAssignment_2(), "rule__Audio__NameAssignment_2");
			builder.put(grammarAccess.getAudioAccess().getDescriptionAssignment_4_1(), "rule__Audio__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAudioAccess().getLienAssignment_6(), "rule__Audio__LienAssignment_6");
			builder.put(grammarAccess.getAudioAccess().getDureeAssignment_7_1(), "rule__Audio__DureeAssignment_7_1");
			builder.put(grammarAccess.getNiveauAccess().getUnorderedGroup_4(), "rule__Niveau__UnorderedGroup_4");
			builder.put(grammarAccess.getFormationAccess().getUnorderedGroup_4(), "rule__Formation__UnorderedGroup_4");
			builder.put(grammarAccess.getUEAccess().getUnorderedGroup_4(), "rule__UE__UnorderedGroup_4");
			builder.put(grammarAccess.getS1Access().getUnorderedGroup_3(), "rule__S1__UnorderedGroup_3");
			builder.put(grammarAccess.getS2Access().getUnorderedGroup_3(), "rule__S2__UnorderedGroup_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LangFilGrammarAccess grammarAccess;

	@Override
	protected InternalLangFilParser createParser() {
		InternalLangFilParser result = new InternalLangFilParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LangFilGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LangFilGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
